### ISSUE TITLE
Error in rule download_eggNOG_fastas

### ISSUE THREAD

**Issue by jmtsuji** [metagenome-atlas/atlas#182]
Hi @SilasK 

I'm using ATLAS 2.0.6 on a Ubuntu 18.04 server (non-cluster).

I used the same database directory as I've used when testing ATLAS 2.0.0 to 2.0.3. However, some of the download rules were run again, I think because the download directory structure has been reorganized (e.g., `OG_fasta`).

An error occurred in `rule download_eggNOG_fastas`. Here is the end of the logfile (what was printed to the screen):

```
localrule download_eggNOG_fastas:
    output: /Data/reference_databases/atlas/2.0.0/EggNOG/OG_fasta
    jobid: 74
    reason: Forced execution
curl 'http://eggnogdb.embl.de/download/emapperdb-4.5.1/OG_fasta.tar.gz' -s > /Data/reference_databases/atlas/2.0.0/EggNOG/OG_fasta.tar.gz

tar -zxf /Data/reference_databases/atlas/2.0.0/EggNOG/OG_fasta.tar.gz --directory /Data/reference_databases/atlas/2.0.0/EggNOG
[Thu Mar  7 23:28:31 2019]
Error in rule download_eggNOG_fastas:
    jobid: 0
    output: /Data/reference_databases/atlas/2.0.0/EggNOG/OG_fasta

Traceback (most recent call last):
  File "/Analysis/jmtsuji/miniconda3_mellea/envs/atlas_2.0.6/lib/python3.6/site-packages/snakemake/executors.py", line 357, in _callback
    callback(job)
  File "/Analysis/jmtsuji/miniconda3_mellea/envs/atlas_2.0.6/lib/python3.6/site-packages/snakemake/scheduler.py", line 315, in _proceed
    self.get_executor(job).handle_job_success(job)
  File "/Analysis/jmtsuji/miniconda3_mellea/envs/atlas_2.0.6/lib/python3.6/site-packages/snakemake/executors.py", line 370, in handle_job_success
    super().handle_job_success(job)
  File "/Analysis/jmtsuji/miniconda3_mellea/envs/atlas_2.0.6/lib/python3.6/site-packages/snakemake/executors.py", line 151, in handle_job_success
    assume_shared_fs=self.assume_shared_fs)
  File "/Analysis/jmtsuji/miniconda3_mellea/envs/atlas_2.0.6/lib/python3.6/site-packages/snakemake/jobs.py", line 885, in postprocess
    self.dag.handle_protected(self)
  File "/Analysis/jmtsuji/miniconda3_mellea/envs/atlas_2.0.6/lib/python3.6/site-packages/snakemake/dag.py", line 450, in handle_protected
    f.protect()
  File "/Analysis/jmtsuji/miniconda3_mellea/envs/atlas_2.0.6/lib/python3.6/site-packages/snakemake/io.py", line 358, in protect
    lchmod(os.path.join(self.file, f), mode)
  File "/Analysis/jmtsuji/miniconda3_mellea/envs/atlas_2.0.6/lib/python3.6/site-packages/snakemake/io.py", line 62, in lchmod
    follow_symlinks=os.chmod not in os.supports_follow_symlinks)
FileNotFoundError: [Errno 2] No such file or directory: '/Data/reference_databases/atlas/2.0.0/EggNOG/OG_fasta/14XIR.fa'
exception calling callback for <Future at 0x7f4462414e48 state=finished returned NoneType>
Traceback (most recent call last):
  File "/Analysis/jmtsuji/miniconda3_mellea/envs/atlas_2.0.6/lib/python3.6/site-packages/snakemake/executors.py", line 357, in _callback
    callback(job)
  File "/Analysis/jmtsuji/miniconda3_mellea/envs/atlas_2.0.6/lib/python3.6/site-packages/snakemake/scheduler.py", line 315, in _proceed
    self.get_executor(job).handle_job_success(job)
  File "/Analysis/jmtsuji/miniconda3_mellea/envs/atlas_2.0.6/lib/python3.6/site-packages/snakemake/executors.py", line 370, in handle_job_success
    super().handle_job_success(job)
  File "/Analysis/jmtsuji/miniconda3_mellea/envs/atlas_2.0.6/lib/python3.6/site-packages/snakemake/executors.py", line 151, in handle_job_success
    assume_shared_fs=self.assume_shared_fs)
  File "/Analysis/jmtsuji/miniconda3_mellea/envs/atlas_2.0.6/lib/python3.6/site-packages/snakemake/jobs.py", line 885, in postprocess
    self.dag.handle_protected(self)
  File "/Analysis/jmtsuji/miniconda3_mellea/envs/atlas_2.0.6/lib/python3.6/site-packages/snakemake/dag.py", line 450, in handle_protected
    f.protect()
  File "/Analysis/jmtsuji/miniconda3_mellea/envs/atlas_2.0.6/lib/python3.6/site-packages/snakemake/io.py", line 358, in protect
    lchmod(os.path.join(self.file, f), mode)
  File "/Analysis/jmtsuji/miniconda3_mellea/envs/atlas_2.0.6/lib/python3.6/site-packages/snakemake/io.py", line 62, in lchmod
    follow_symlinks=os.chmod not in os.supports_follow_symlinks)
FileNotFoundError: [Errno 2] No such file or directory: '/Data/reference_databases/atlas/2.0.0/EggNOG/OG_fasta/14XIR.fa'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Analysis/jmtsuji/miniconda3_mellea/envs/atlas_2.0.6/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/Analysis/jmtsuji/miniconda3_mellea/envs/atlas_2.0.6/lib/python3.6/site-packages/snakemake/executors.py", line 367, in _callback
    error_callback(job)
  File "/Analysis/jmtsuji/miniconda3_mellea/envs/atlas_2.0.6/lib/python3.6/site-packages/snakemake/scheduler.py", line 346, in _error
    self._handle_error(job)
  File "/Analysis/jmtsuji/miniconda3_mellea/envs/atlas_2.0.6/lib/python3.6/site-packages/snakemake/scheduler.py", line 355, in _handle_error
    self.get_executor(job).handle_job_error(job)
  File "/Analysis/jmtsuji/miniconda3_mellea/envs/atlas_2.0.6/lib/python3.6/site-packages/snakemake/executors.py", line 374, in handle_job_error
    job.cleanup()
  File "/Analysis/jmtsuji/miniconda3_mellea/envs/atlas_2.0.6/lib/python3.6/site-packages/snakemake/jobs.py", line 697, in cleanup
    f.remove()
  File "/Analysis/jmtsuji/miniconda3_mellea/envs/atlas_2.0.6/lib/python3.6/site-packages/snakemake/io.py", line 363, in remove
    remove(self, remove_non_empty_dir=True)
  File "/Analysis/jmtsuji/miniconda3_mellea/envs/atlas_2.0.6/lib/python3.6/site-packages/snakemake/io.py", line 545, in remove
    shutil.rmtree(file)
  File "/Analysis/jmtsuji/miniconda3_mellea/envs/atlas_2.0.6/lib/python3.6/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/Analysis/jmtsuji/miniconda3_mellea/envs/atlas_2.0.6/lib/python3.6/shutil.py", line 418, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/Analysis/jmtsuji/miniconda3_mellea/envs/atlas_2.0.6/lib/python3.6/shutil.py", line 438, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/Analysis/jmtsuji/miniconda3_mellea/envs/atlas_2.0.6/lib/python3.6/shutil.py", line 436, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: '14XIR.fa'
```

The key messages seem to be:
```
FileNotFoundError: [Errno 2] No such file or directory: '/Data/reference_databases/atlas/2.0.0/EggNOG/OG_fasta/14XIR.fa'

PermissionError: [Errno 13] Permission denied: '14XIR.fa'
```

This file is actually nested in a subfolder, in `/Data/reference_databases/atlas/2.0.0/EggNOG/OG_fasta/perNOG/14XIR.fa`

Is `rule download_eggNOG_fastas` looking for these output files and searching in the wrong directory? Could this be related to trying to change their permissions, from `protected()` in `protected(directory(f"{EGGNOG_DIR}/OG_fasta")),` in commit 85598a6, line 99?

It's not ideal, but I removed `protected()` from the output line, and the rule finished without issue.

Jackson

**Comment by SilasK** [comment]
No I think you are right. This protected flags doing more harm than good.
I should remove them.

**Comment by SilasK** [comment]
@jmtsuji  Can you open a PR? and remove all the protected flags in the download.snakefile ?

**Comment by jmtsuji** [comment]
PR created
