### ISSUE TITLE
Errors with QC init

### ISSUE THREAD

**Issue by mradz19** [metagenome-atlas/atlas#226]
I'm having issues with several samples during the QC step. **The QC log files show this message for one sample:**

Error in ../run3_HH3_S67_M_R1_001.fastq.gz, line 60880403, with these 4 lines:
@D00116:347:CDV3RANXX:7:2304:16920:27219 1:N:0:GGACTCCT+TATCCTCN
GAATAGAATGGAATCGTCGAAAGAAATCGAATGGAATCATCATCGAATGAAATCAAATGGAATTATCATATGGACTGGAATGGAATCATCATCGAATGGAATTGAATGGAATCATCGAATGGAFBFFF<<FFFFFFFF
@D00116:347:CDV3RANXX:7:2304:10867:28874 1:N:0:GGACTCCT+TATCCTCN
GATAGTATGTGGCTTTCTCAGATTGTTGTTTTTTTCACTTTGAAATATGTGTTTAAGATCTATCCCTTTTTATGGCTTGATAGCTCCATTATGTTTATCACTGAATAATAGTTCATTATATTGATT

	at stream.FASTQ.quadToRead(FASTQ.java:782)
	at stream.FASTQ.toReadList(FASTQ.java:711)
	at stream.FastqReadInputStream.fillBuffer(FastqReadInputStream.java:109)
	at stream.FastqReadInputStream.nextList(FastqReadInputStream.java:94)
	at stream.ConcurrentGenericReadInputStream$ReadThread.readLists(ConcurrentGenericReadInputStream.java:677)
	at stream.ConcurrentGenericReadInputStream$ReadThread.run(ConcurrentGenericReadInputStream.java:653)
Input:                  	30440000 reads          	3392553318 bases
Output:                 	30440000 reads (100.00%) 	3392553318 bases (100.00%)

Time:                         	169.502 seconds.
Reads Processed:      30440k 	179.59k reads/sec
Bases Processed:       3392m 	20.01m bases/sec
Names appear to be correctly paired.
Exception in thread "main" java.lang.RuntimeException: ReformatReads terminated in an error state; the output may be corrupt.
	at jgi.ReformatReads.process(ReformatReads.java:1173)
	at jgi.ReformatReads.main(ReformatReads.java:45)

**And this message for another sample:**

java -ea -Xmx8G -cp run_3_test/databases/conda_envs/de317ea9/opt/bbmap-37.78/current/ jgi.ReformatReads 
in1=/run3_HH18_S74_M_R1_001.fastq.gz 
in2=/run3_HH18_S74_M_R2_001.fastq.gz interleaved=f out1=run3-HH18-S74-M-001/sequence_quality_control/run3-HH18-S74-M-001_raw_R1.fastq.gz out2=run3-HH18-S74-M-001/sequence_quality_control/run3-HH18-S74-M-001_raw_R2.fastq.gz iupacToN=t touppercase=t qout=33 overwrite=true verifypaired=t addslash=t trimreaddescription=t threads=4 -Xmx8G
Executing jgi.ReformatReads [in1=/run3_HH18_S74_M_R1_001.fastq.gz, in2=/run3_HH18_S74_M_R2_001.fastq.gz, interleaved=f, out1=run3-HH18-S74-M-001/sequence_quality_control/run3-HH18-S74-M-001_raw_R1.fastq.gz, out2=run3-HH18-S74-M-001/sequence_quality_control/run3-HH18-S74-M-001_raw_R2.fastq.gz, iupacToN=t, touppercase=t, qout=33, overwrite=true, verifypaired=t, addslash=t, trimreaddescription=t, threads=4, -Xmx8G]

Set INTERLEAVED to false
Set threads to 4
Input is being processed as paired
java.lang.Exception: 
Mismatch between length of bases and qualities for read 8872728 (id=D00116:347:CDV3RANXX:7:2306:8677:48843).
# qualities=64, # bases=1048672

BBBBBBBFFFFFFFFFBFFFFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBF
CTCACATCTTATACTAAAATTAATTCAAAATTTATCACAAACTTAAAAGTAACATAACATTCTAAGAATATGAAATGGAATGGAATGGAATGGAAT

This can be bypassed with the flag 'tossbrokenreads' or 'nullifybrokenquality'
	at shared.KillSwitch.kill(KillSwitch.java:99)
	at stream.Read.validateQualityLength(Read.java:208)
	at stream.Read.validate(Read.java:104)
	at stream.Read.<init>(Read.java:76)
	at stream.Read.<init>(Read.java:59)
	at stream.FASTQ.quadToRead(FASTQ.java:879)
	at stream.FASTQ.toReadList(FASTQ.java:711)
	at stream.FastqReadInputStream.fillBuffer(FastqReadInputStream.java:109)
	at stream.FastqReadInputStream.nextList(FastqReadInputStream.java:94)
	at stream.ConcurrentGenericReadInputStream$ReadThread.readLists(ConcurrentGenericReadInputStream.java:677)
	at stream.ConcurrentGenericReadInputStream$ReadThread.run(ConcurrentGenericReadInputStream.java:653)

I'm not sure how to proceed from here.

**Comment by SilasK** [comment]
There are errors in your input file:
> Mismatch between length of bases and qualities for read 8872728 
How did you get your input files? do you want to remove the broken reads? 

For next time consider putting the log as ```code```:  between  2```

**Comment by kuangzhuoran** [comment]
Hi ! I met the same error
Can you tell me how you fix this error? 
I try to add      tossbrokenreads: true     and     nullifybrokenquality: true    in config.yaml
"""
########################
# Quality control 
########################
data_type: metagenome # metagenome or metatranscriptome
interleaved_fastqs: false

# remove (PCR)-duplicated reads using clumpify
deduplicate: true
duplicates_only_optical: false 
duplicates_allow_substitutions: 2
nullifybrokenquality: true
tossbrokenreads: true
"""

but it does not make sense

**Comment by SilasK** [comment]
Use the config argument:

```
importqc_params:  "iupacToN=t touppercase=t qout=33 addslash=t trimreaddescription=t tossbrokenreads=t"
```
Double-check in the logs, how many reads you remove.
