### ISSUE TITLE
Error in run_concot: missing required dependencies ['numpy']

### ISSUE THREAD

**Issue by spleonard1** [metagenome-atlas/atlas#248]
Running atlas on a linux machine, during rule run_concoct atlas breaks with the following error code:

```Activating conda environment: /stor/work/Ochman/sean/projects/bee_metagenomes/databases/conda_envs/b7bf3649
Traceback (most recent call last):
  File "/stor/work/Ochman/sean/projects/bee_metagenomes/databases/conda_envs/b7bf3649/bin/concoct", line 4, in <module>
    __import__('pkg_resources').run_script('concoct==0.4.0', 'concoct')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/stor/work/Ochman/sean/projects/bee_metagenomes/databases/conda_envs/b7bf3649/lib/python2.7/site-packages/concoct-0.4.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/concoct", line 8, in <module>
    from concoct.output import Output
  File "/stor/work/Ochman/sean/projects/bee_metagenomes/databases/conda_envs/b7bf3649/lib/python2.7/site-packages/concoct-0.4.0-py2.7-linux-x86_64.egg/concoct/output.py", line 11, in <module>
    import pandas as p
  File "/usr/lib/python2.7/dist-packages/pandas/__init__.py", line 19, in <module>
    "Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['numpy']
[Sun Oct  6 13:06:56 2019]
Error in rule run_concoct:
    jobid: 92
    output: big-bee-meta1/binning/concoct/intermediate_files/clustering_gt1000.csv
    log: big-bee-meta1/binning/concoct/intermediate_files/log.txt (check log file(s) for error message)
    conda-env: /stor/work/Ochman/sean/projects/bee_metagenomes/databases/conda_envs/b7bf3649
    shell:
        
        concoct -c 200             --coverage_file big-bee-meta1/binning/coverage/combined_coverage.tsv             --composition_file big-bee-meta1/big-bee-meta1_contigs.fasta             --basename big-bee-meta1/binning/concoct/intermediate_files             --read_length 100             --length_threshold 1000             --converge_out             --iterations 500
        
        (exited with non-zero exit code)
```

I don't have much experience with Conda so I don't know how to go in and see if there's something wrong in that environment. I tried uninstalling and reinstalling numpy in the main atlas environment, but no change. The rule log file is empty. Any ideas? Thanks for your help!

**Comment by Leitemfa** [comment]
Hello @SilasK , I also got a similar error at this stage. See it below:

```
Up and running. Check /mnt/nfs/bioinfdata/ngs/ME/kuramae_group/marcio/Atlas-Nodule/MPR1-1n-EST/binning/concoct/intermediate_files/log.txt for progress
Traceback (most recent call last):
  File "/mnt/nfs/bioinfdata/ngs/ME/kuramae_group/marcio/AtlasNitrospira/RefFiles/conda_envs/a3f55175/bin/concoct", line 4, in <module>
    __import__('pkg_resources').run_script('concoct==0.4.0', 'concoct')
  File "/mnt/nfs/bioinfdata/ngs/ME/kuramae_group/marcio/AtlasNitrospira/RefFiles/conda_envs/a3f55175/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/mnt/nfs/bioinfdata/ngs/ME/kuramae_group/marcio/AtlasNitrospira/RefFiles/conda_envs/a3f55175/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/mnt/nfs/bioinfdata/ngs/ME/kuramae_group/marcio/AtlasNitrospira/RefFiles/conda_envs/a3f55175/lib/python2.7/site-packages/concoct-0.4.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/concoct", line 76, in <module>
    results = main(args)
  File "/mnt/nfs/bioinfdata/ngs/ME/kuramae_group/marcio/AtlasNitrospira/RefFiles/conda_envs/a3f55175/lib/python2.7/site-packages/concoct-0.4.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/concoct", line 20, in main
    composition, cov, cov_range = load_data(args)
  File "/mnt/nfs/bioinfdata/ngs/ME/kuramae_group/marcio/AtlasNitrospira/RefFiles/conda_envs/a3f55175/lib/python2.7/site-packages/concoct-0.4.0-py2.7-linux-x86_64.egg/concoct/input.py", line 16, in load_data
    args.length_threshold
  File "/mnt/nfs/bioinfdata/ngs/ME/kuramae_group/marcio/AtlasNitrospira/RefFiles/conda_envs/a3f55175/lib/python2.7/site-packages/concoct-0.4.0-py2.7-linux-x86_64.egg/concoct/input.py", line 70, in load_composition
    kmer_len
  File "/mnt/nfs/bioinfdata/ngs/ME/kuramae_group/marcio/AtlasNitrospira/RefFiles/conda_envs/a3f55175/lib/python2.7/site-packages/concoct-0.4.0-py2.7-linux-x86_64.egg/concoct/input.py", line 49, in _calculate_composition
    in window(seq.seq.tostring().upper(), kmer_len)
AttributeError: 'Seq' object has no attribute 'tostring'
[Mon Oct  7 13:36:18 2019]
Error in rule run_concoct:
    jobid: 888
    output: MPR1-1n-EST/binning/concoct/intermediate_files/clustering_gt1000.csv
    log: MPR1-1n-EST/binning/concoct/intermediate_files/log.txt (check log file(s) for error message)
    conda-env: /mnt/nfs/bioinfdata/ngs/ME/kuramae_group/marcio/AtlasNitrospira/RefFiles/conda_envs/a3f55175
    shell:

        concoct -c 200             --coverage_file MPR1-1n-EST/binning/coverage/combined_coverage.tsv             --composition_file MPR1-1n-EST/MPR1-1n-EST_contigs.fasta             --basename MPR1-1n-EST/binning/concoct/intermediate_files             --read_length 100             --length_threshold 1000             --converge_out             --iterations 500

        (exited with non-zero exit code)
```

I also attached my log file
[Uploading log.txt…]()

**Comment by SilasK** [comment]
I don’t know why the condo env of concept is broken.
I’ve seen there is a new version (1.1), but we will need to adapt the scripts.

For now I think it would be easier to drop concoct. Modify the config file in the binning section.

In my experiences end in publication e.g. DAS Tool, concoct was not the best binner. Or do you need concoct?

**Comment by spleonard1** [comment]
I have no attachment to concoct so  I dropped it from the config.yaml and it seems to be working fine.  Thanks!
