### ISSUE TITLE
--skip-qc with lowercase fastq files generate error in align2.BBMap

### ISSUE THREAD

**Issue by noirot** [metagenome-atlas/atlas#278]
Hi,
I'm trying to run ATLAS on mock data. If I skip qc (has it filter most of my data), then BBmap crash because reads are in lowercase and genome uppercase
```
Executing align2.BBMap [build=1, overwrite=true, fastareadlen=500, nodisk=t, trimreaddescriptions=t, threads=8, pairlen=1000, pairedonly=t, minid=0.76, mdtag=t, xstag=fs, nmtag=t, sam=1
.3, local=t, ambiguous=all, secondary=t, saa=f, append=t, machineout=t, maxsites=10, ref=mockgut-1M/assembly/mockgut-1M_prefilter_contigs.fasta, in=/work2/genphyse/NED_metaG/processing/
atlas/data_m1/mockgut_1M_R1.fastq, out=mockgut-1M/sequence_alignment/alignment_to_prefilter_contigs.sam, in2=/work2/genphyse/NED_metaG/processing/atlas/data_m1/mockgut_1M_R2.fastq]
Version 37.99 [build=1, overwrite=true, fastareadlen=500, nodisk=t, trimreaddescriptions=t, threads=8, pairlen=1000, pairedonly=t, minid=0.76, mdtag=t, xstag=fs, nmtag=t, sam=1.3, local
=t, ambiguous=all, secondary=t, saa=f, append=t, machineout=t, maxsites=10, ref=mockgut-1M/assembly/mockgut-1M_prefilter_contigs.fasta, in=/work2/genphyse/NED_metaG/processing/atlas/dat
a_m1/mockgut_1M_R1.fastq, out=mockgut-1M/sequence_alignment/alignment_to_prefilter_contigs.sam, in2=/work2/genphyse/NED_metaG/processing/atlas/data_m1/mockgut_1M_R2.fastq]

Set threads to 8
Retaining all best sites for ambiguous mappings.
Set MINIMUM_ALIGNMENT_SCORE_RATIO to 0.559
Executing dna.FastaToChromArrays2 [mockgut-1M/assembly/mockgut-1M_prefilter_contigs.fasta, 1, writeinthread=false, genscaffoldinfo=true, retain, waitforwriting=false, gz=true, maxlen=53
6670912, writechroms=false, minscaf=1, midpad=300, startpad=8000, stoppad=8000, nodisk=true]

Set genScaffoldInfo=true
Set genome to 1

Loaded Reference:	0.035 seconds.
Loading index for chunk 1-1, build 1
Indexing threads started for block 0-1
Indexing threads finished for block 0-1
Generated Index:	2.198 seconds.
Analyzed Index:   	2.501 seconds.
Started output stream:	0.224 seconds.
Cleared Memory:    	0.106 seconds.
Processing reads in paired-ended mode.
Started read stream.
Started 8 mapping threads.
Exception in thread "Thread-13" Exception in thread "Thread-6" java.lang.AssertionError: Lowercase letters detected: ref=G, read=g
gcccggcctcggcttcaagaaatccggaacatacgtcggcttcgacgtggacgtggccaagtacgtcgccaagaagctcggctattccgaagacgagatcgtctggaaggaagccccctc
Please re-run with the 'tuc=t' flag (touppercase=true).
	at stream.SiteScore.isPerfect(SiteScore.java:223)
	at align2.AbstractMapThread.genMatchStringForSite(AbstractMapThread.java:997)
	at align2.AbstractMapThread.genMatchString(AbstractMapThread.java:901)
	at align2.BBMapThread.processReadPair(BBMapThread.java:1231)
	at align2.AbstractMapThread.run(AbstractMapThread.java:515)
Exception in thread "Thread-12" java.lang.AssertionError: Lowercase letters detected: ref=A, read=a
agccgatgccggtcgcctcccatgccttcggatacatggagatcggcgtgaaaccgggcatcgtgttgatctcattgaccatcacctcgccgtccggcgtcacgaacgtgtccacgcggc
Please re-run with the 'tuc=t' flag (touppercase=true).
	at stream.SiteScore.isPerfect(SiteScore.java:223)
	at align2.AbstractMapThread.genMatchStringForSite(AbstractMapThread.java:997)
	at align2.AbstractMapThread.genMatchString(AbstractMapThread.java:901)
	at align2.BBMapThread.processReadPair(BBMapThread.java:1231)
	at align2.AbstractMapThread.run(AbstractMapThread.java:515)
java.lang.AssertionError: Lowercase letters detected: ref=C, read=c
cccacgaccatgtcagaaccgcgcctggcacagggcaaagtcggcaagacggcgcaacaacaacatctaccgacgcacgtcgaagacccacacggcccacgtcttggtcatacggccgca
```
I think it could be avoid with option 'tuc=t' ?

**Comment by SilasK** [comment]
So I would need an extra flag for all bbmap steps.

**Comment by SilasK** [comment]
Is this still a problem? Or do you think it’s only a feature of your mock data? When you use the qc workflow the uppercase get’s corrected isn’t it?

**Comment by noirot** [comment]
The pb come from my mock, but anybody with lowercase fastq will have the pb.
