### ISSUE TITLE
Error with MaxBin

### ISSUE THREAD

**Issue by noirot** [metagenome-atlas/atlas#284]
I finally try to run atlas with yours example data.

Atlas stopped at binning step. Log of maxbin was empty to get the error, I loaded env as written in main log file, and get the following error:

```run_MaxBin.pl -contig sample2/sample2_contigs.fasta             -abund sample2/binning/coverage/sample2_coverage.txt -out sample2/binning/maxbin/intermediate_files/sample2             -min_contig_length 1000             -thread 8             -prob_threshold 0.9             -max_iteration 50 >> sample2/logs/binning/maxbin.log
perl: symbol lookup error: /tools/perl5/modules/lib/perl5/x86_64-linux-thread-multi/auto/Cwd/Cwd.so: undefined symbol: Perl_xs_version_bootcheck
```

Here is how I launch the whole workflow :
```
module load system/Miniconda3-4.7.10
module load system/Python-3.4.3

source activate atlasenv
atlas init --interleaved-fastq --db-dir <....>/atlas-test-data/databases example_data/reads/test/
atlas run all --profile cluster
```

Please ... help here is my last try ...

**Comment by SilasK** [comment]
This seems to be a confusing between the perl from your system modules and the one installed with conda.

> /tools/perl5/modules/lib/perl5/x86_64-linux-thread-multi/auto/Cwd/Cwd.so:

Make sure no module except the miniconda is loaded.
I think you don’t need the python module either


Maybe you can ask your system admin.

**Comment by SilasK** [comment]
If you are in the maxbin environment, and you run `which perl` what do you get?

**Comment by noirot** [comment]
My system admin advice me to execute before load atlasenv:
```unset PERL5LIB```

Thus the pipeline run until gtdb and I get the error: 
```
Path_atlas-test-data $ more genomes/taxonomy/gtdb/gtdbtk.log
[2020-02-26 15:16:53] INFO: GTDB-Tk v1.0.2
[2020-02-26 15:16:53] INFO: gtdbtk classify --genome_dir genomes/genomes --align_dir genomes/taxonomy/gtdb --out_dir genomes/taxonomy/gtdb --extension fasta --cpus 8
[2020-02-26 15:16:53] INFO: Using GTDB-Tk reference data version r89: /work2/genphyse/NED_metaG/processing/atlas-test-data/databases/GTDB-TK
[2020-02-26 15:16:53] INFO: Placing 3 bacterial genomes into reference tree with pplacer (be patient).
[2020-02-26 15:29:01] ERROR: Controlled exit resulting from an unrecoverable error or warning.

================================================================================
EXCEPTION: PplacerException
  MESSAGE: An error was encountered while running pplacer, check the log file: genomes/taxonomy/gtdb/classify/intermediate_results/pplacer/pplacer.bac120.out
________________________________________________________________________________

Traceback (most recent call last):
  File "/work2/genphyse/NED_metaG/processing/atlas-test-data/databases/conda_envs/3de9e491/bin/gtdbtk", line 449, in <module>
    gt_parser.parse_options(args)
  File "/work2/genphyse/NED_metaG/processing/atlas-test-data/databases/conda_envs/3de9e491/lib/python3.8/site-packages/gtdbtk/main.py", line 633, in parse_options
    self.classify(options)
  File "/work2/genphyse/NED_metaG/processing/atlas-test-data/databases/conda_envs/3de9e491/lib/python3.8/site-packages/gtdbtk/main.py", line 409, in classify
    classify.run(genomes,
  File "/work2/genphyse/NED_metaG/processing/atlas-test-data/databases/conda_envs/3de9e491/lib/python3.8/site-packages/gtdbtk/classify.py", line 345, in run
    classify_tree = self.place_genomes(user_msa_file,
  File "/work2/genphyse/NED_metaG/processing/atlas-test-data/databases/conda_envs/3de9e491/lib/python3.8/site-packages/gtdbtk/classify.py", line 163, in place_genomes
    pplacer.run(self.cpus, 'WAG', pplacer_ref_pkg, pplacer_json_out,
  File "/work2/genphyse/NED_metaG/processing/atlas-test-data/databases/conda_envs/3de9e491/lib/python3.8/site-packages/gtdbtk/external/pplacer.py", line 154, in run
    raise PplacerException('An error was encountered while '
gtdbtk.exceptions.PplacerException: An error was encountered while running pplacer, check the log file: genomes/taxonomy/gtdb/classify/intermediate_results/pplacer/pplacer.bac120.out
================================================================================
```
Finaly the pipeline is finished by removing this step in config file.
```
annotations:
- gtdb_tree
#- gtdb_taxonomy
```
But do you have an idea of the reason of the pb with pplacer ? Or where I can find the intermediate_results ?

**Comment by SilasK** [comment]
Great, you found a way to solve the problem with the perl lib.

GTDB or more specifically , the placer needs a lot of memory.
I guessed 100gb, this is what large_mem in the config file defines.

If you don’t have so much memory you might want to use the checkm_taxonomy under annotations.

annotations:
- gtdb_tree
#- gtdb_taxonomy
- genes
- checkm_taxonomy
- checkm_tree



Any case the intermediate results (alignments of marker genes) are in: genomes/taxonomy/gtdb

**Comment by noirot** [comment]
As Atlas runs with example data, I'm trying to run on the mock data, but I get the following message:
```
No bins detected with binner metabat in sample mockgut-5M.
This will break the continuationof the pipeline. Check what happened. Maybe the the assembly is too small. You can either remove the binner (for all samples) from the config.yaml file or the sample from the sample.tsv
```

So how to change config.yaml file ? I commented all line corresponding to binning but pipeline still stop with the same message.

**Comment by SilasK** [comment]
Why not start using a real microbiome instead of a mock sample, you can also take a public one.

If out comment all lines, the default will be applied, which is what is written in the config file at the beginning.

What you can do if this happens is to select
final_binner: maxbin

But I’m not sure if maxbin would be able to bin if metabat cannot.

Using spades for assembly usually gives better assemblies.

**Comment by SilasK** [comment]
if you have any question you can re-open the issue
