### ISSUE TITLE
ATLAS unable to read qstat output in pbs_status.py

### ISSUE THREAD

**Issue by RyloByte** [metagenome-atlas/atlas#323]
Hey ATLAS-dev team,
First thanks for the immense effort building this workflow! I'm very excited to start using it for analysis!
I have recently tried to install/test ATLAS version 2.4.3 on a grid cluster which uses PBSpro version 19.1.3.
I successfully built the env and database. I then used cookiecutter to config the cluster settings for snakemake.
I then started a screen and ran `atlas run -w [path to my outdir]/ -c [path to my config]/config.yaml -j 20 --profile cluster all`
It seemed that the first jobs fired off just fine, but I got an error when ATLAS tried to check the status of the jobs using `pbs_status.py`.
Here is the complete error I recieved:
```
Submitted job 226 with external jobid '1289131'.
Traceback (most recent call last):
  File "/home/mcglock/.config/snakemake/cluster/pbs_status.py", line 12, in <module>
    xmldoc = ET.ElementTree(ET.fromstring(res.stdout.decode())).getroot()
  File "/home/mcglock/anaconda3/envs/atlasenv/lib/python3.6/xml/etree/ElementTree.py", line 1314, in XML 
    parser.feed(text)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/mcglock/anaconda3/envs/atlasenv/lib/python3.6/site-packages/snakemake/executors.py", line 911, in job_status
    shell=True,
  File "/home/mcglock/anaconda3/envs/atlasenv/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/home/mcglock/anaconda3/envs/atlasenv/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '/home/mcglock/.config/snakemake/cluster/pbs_status.py 1289125' returned non-zero exit status 1.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/mcglock/anaconda3/envs/atlasenv/lib/python3.6/threading.py", line 916, in _bootstrap_inner 
    self.run()
  File "/home/mcglock/anaconda3/envs/atlasenv/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mcglock/anaconda3/envs/atlasenv/lib/python3.6/site-packages/snakemake/executors.py", line 954, in _wait_for_jobs
    status = job_status(active_job)
  File "/home/mcglock/anaconda3/envs/atlasenv/lib/python3.6/site-packages/snakemake/executors.py", line 927, in job_status
    "Failed to obtain job status. "
snakemake.exceptions.WorkflowError: Failed to obtain job status. See above for error message.
```
After some internet sleuthing I managed to figure out that, as far as I can tell, the version of `qstat` that I am using doesn't output the expected XML format that `pbs_status.py` needs. So then I cracked open that script and edited it so that it could read in the JSON format qstat output from my system.
Here is the quick and dirty from that:
```
#!/usr/bin/env python3

import sys
import subprocess
import xml.etree.cElementTree as ET
import json as JS

jobid = sys.argv[1]

try:
    res = subprocess.run("qstat -f -F json -x {}".format(jobid), check=True, stdout=subprocess.PIPE,$
    jsondoc = JS.loads(res.stdout.decode().replace('"""', '"'))
    #xmldoc = ET.ElementTree(ET.fromstring(res.stdout.decode())).getroot()
    #job_state = xmldoc.findall('.//job_state')[0].text
    jobs = jsondoc["Jobs"]
    job_state = jobs[list(jobs.keys())[0]]["job_state"]
    if job_state == "F":
        #exit_status = xmldoc.findall('.//exit_status')[0].text
        exit_status = jobs[list(jobs.keys())[0]]["Exit_status"]
        if exit_status == 0:
            print("success")
        else:
            print("failed")
    else:
	print("running")

except (subprocess.CalledProcessError, IndexError, KeyboardInterrupt) as e:
    print("failed")
```
As far as I can tell that allowed ATLAS to proceed past the first job status checking and the workflow continued. Not sure if my edits will be helpful for you, but I figured couldn't hurt to send them along.
Thanks again for your huge effort building and maintaining this workflow!

**Comment by SilasK** [comment]
Thank, you very much. It's not often that an Issue comes with the solution. Could you tell me what is the full content of the first line after the try:. It seems to be cut off. Thank you in advance.

**Comment by McGlock** [comment]
Sorry about that! Forgot to line wrap!
```
#!/usr/bin/env python3

import sys
import subprocess
import xml.etree.cElementTree as ET
import json as JS

jobid = sys.argv[1]

try:
    res = subprocess.run("qstat -f -F json -x {}".format(jobid), check=True, stdout=subprocess.PIPE, 
stderr=subprocess.STDOUT, shell=True)
    jsondoc = JS.loads(res.stdout.decode().replace('"""', '"'))
    #xmldoc = ET.ElementTree(ET.fromstring(res.stdout.decode())).getroot()
    #job_state = xmldoc.findall('.//job_state')[0].text
    jobs = jsondoc["Jobs"]
    job_state = jobs[list(jobs.keys())[0]]["job_state"]
    if job_state == "F":
        #exit_status = xmldoc.findall('.//exit_status')[0].text
        exit_status = jobs[list(jobs.keys())[0]]["Exit_status"]
        if exit_status == 0:
            print("success")
        else:
            print("failed")
    else:
	print("running")

except (subprocess.CalledProcessError, IndexError, KeyboardInterrupt) as e:
    print("failed")
```
