### ISSUE TITLE
Error in rule initialize_qc

### ISSUE THREAD

**Issue by johanneswerner** [metagenome-atlas/atlas#358]
Hello, 

I get an error when running ATLAS with some of my samples. 

```
Error in rule initialize_qc:
    jobid: 1106
    output: SRR6853352/sequence_quality_control/SRR6853352_raw_R1.fastq.gz, SRR6853352/sequence_quality_control/SRR6853352_raw_R2.fastq.gz
    log: SRR6853352/logs/QC/init.log (check log file(s) for error message)
    conda-env: /data/db_atlas/conda_envs/b63ee61f
    shell:
        
        reformat.sh in1=/.../raw/SRR6853352_R1.fastq.gz in2=/.../raw/SRR6853352_R2.fastq.gz             interleaved=f             out1=SRR6853352/sequence_quality_control/SRR6853352_raw_R1.fastq.gz out2=SRR6853352/sequence_quality_control/SRR6853352_raw_R2.fastq.gz             iupacToN=t touppercase=t qout=33 addslash=t trimreaddescription=t             overwrite=true             verifypaired=t             threads=1             -Xmx8G 2> SRR6853352/logs/QC/init.log
        
        (exited with non-zero exit code)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Note the path to the log file for debugging.
Documentation is available at: https://metagenome-atlas.readthedocs.io
Issues can be raised at: https://github.com/metagenome-atlas/atlas/issues
Complete log: /.../.snakemake/log/2021-01-15T141550.370936.snakemake.log
[2021-01-15 15:28 CRITICAL] Command 'snakemake --snakefile /home/ubuntu/miniconda3/envs/atlas/lib/python3.6/site-packages/atlas/Snakefile --directory /...  --rerun-incomplete --configfile '/.../config.yaml' --nolock   --use-conda --conda-prefix /data/db_atlas/conda_envs   all   ' returned non-zero exit status 1.
```

The content of the log file `SRR6853352/logs/QC/init.log`

```
java -ea -Xmx8G -cp /data/db_atlas/conda_envs/b63ee61f/opt/bbmap-37.99/current/ jgi.ReformatReads in1=/.../raw/SRR6853352_R1.fastq.gz in2=/.../raw
/SRR6853352_R2.fastq.gz interleaved=f out1=SRR6853352/sequence_quality_control/SRR6853352_raw_R1.fastq.gz out2=SRR6853352/sequence_quality_control/SRR6853352_raw_R2.f
astq.gz iupacToN=t touppercase=t qout=33 addslash=t trimreaddescription=t overwrite=true verifypaired=t threads=1 -Xmx8G
Executing jgi.ReformatReads [in1=/.../raw/SRR6853352_R1.fastq.gz, in2=/.../raw/SRR6853352_R2.fastq.gz, interleaved=f, out1=SRR6853352/sequence_qua
lity_control/SRR6853352_raw_R1.fastq.gz, out2=SRR6853352/sequence_quality_control/SRR6853352_raw_R2.fastq.gz, iupacToN=t, touppercase=t, qout=33, addslash=t, trimread
description=t, overwrite=true, verifypaired=t, threads=1, -Xmx8G]

Set INTERLEAVED to false
Set threads to 1
Changed from ASCII-33 to ASCII-64 on input quality B (Q66) for base N at lines 1 and 3, position 82 while prescanning.
Changed from ASCII-64 to ASCII-33 on input quality / (Q47) for base N at lines 1 and 3, position 88 while prescanning.
Exception in thread "main" java.lang.AssertionError: ASCII encoding for quality (currently ASCII-33) appears to be wrong 
for input quality 16 for base N at lines 1 and 3, position 88.
@SRR6853352.1 1/1
/</BBFF<FFFFBFBB<FFBF<BBBFFFFFFBFFF/7BFBB<BBB<<<FFFF<</</<FFBBFFFFB<FF<<FFFF<<FF</BFFFBF/FBF<F/F/FBF#
[47, 60, 47, 66, 66, 70, 70, 60, 70, 70, 70, 70, 66, 70, 66, 66, 60, 70, 70, 66, 70, 60, 66, 66, 66, 70, 70, 70, 70, 70, 70, 66, 70, 70, 70, 47, 55, 66, 70, 66, 66, 6
0, 66, 66, 66, 60, 60, 60, 70, 70, 70, 70, 60, 60, 47, 60, 47, 60, 70, 70, 66, 66, 70, 70, 70, 70, 66, 60, 70, 70, 60, 60, 70, 70, 70, 70, 60, 60, 70, 70, 60, 47, 66,
 70, 70, 70, 66, 70, 47, 70, 66, 70, 60, 70, 47, 70, 47, 70, 66, 70, 35]
        at stream.FASTQ.testQuality(FASTQ.java:230)
        at stream.FASTQ.isInterleaved(FASTQ.java:130)
        at stream.FastqReadInputStream.<init>(FastqReadInputStream.java:58)
        at stream.ConcurrentReadInputStream.getReadInputStream(ConcurrentReadInputStream.java:121)
        at stream.ConcurrentReadInputStream.getReadInputStream(ConcurrentReadInputStream.java:55)
        at jgi.ReformatReads.process(ReformatReads.java:382)
        at jgi.ReformatReads.main(ReformatReads.java:46)
```

When I look into the first few sequences

```
@SRR6853352.1 1/1
GGGTCTTACCTTTCATGGAGAAACGTCGAATCCCCAGCACATCTCTCCCACCATTGAACAATCTCTCGATATCNNNNNNNNNNNNNNNNNNNNNNNNNNNN
+
/</BBFF<FFFFBFBB<FFBF<BBBFFFFFFBFFF/7BFBB<BBB<<<FFFF<</</<FFBBFFFFB<FF<<FFFF<<FF</BFFFBF/FBF<F/F/FBF#
@SRR6853352.2 2/1
CGCAAACCATGCTGAGCGGCGTGCCGTCCGGAGCGTAGAAGGGCTGGCCGCGCAGCTCGACCCAGCGCACCTCGCCGGAGGGCATGTTCACCCGGTACTCG
+
BBBB/BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB
@SRR6853352.3 3/1
CCGCGGAGAGAGCAGATTCAAGGGTTTGCTGTCCAAGGANNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
+
BB/<BFFFFF<B<FFFFFFFFFFFBBFFFFBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFFFFBFFBBFFFFFFFFFF<<F<FFFFFF/FF/FFF#
@SRR6853352.4 4/1
CAATGCCACCTCGGAAATGGTCCGTAACGACTTTCCCGCCGAGAATGGTTTCATCCACAAGCCCCTCCACATGCTTGGGCTCAATGCGGCCATACCAAATT
+
BB<<BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFF
@SRR6853352.5 5/1
TGTCGAGCTCGACACTGATCGTATATCCCGTACCCCTCCCCGCCTCGTTGGAATGGGTGGTGTTTGCCACTCGGTTGAATTTTGCTTCCGTCCCTGGCGGG
+
BBBB/FBFFFFFF<FFFFFFFFF/<<FFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFF<FFFFFFFFFFFFFFBFFFFFF<FFBFFBF<FFFFFFFFFFFF
```

I wonder if it is because of the N bases in the sequencing data. 

Do you have any idea what triggers the error and how to fix it?

Thank you very much for your help and the nifty tool!

**Comment by SilasK** [comment]
Do you use somewhat old sequences? 
As I understand atlas doesn't understand which encoding of the quality values are used. ASCII-33 (sanger) and ASCII-64 (old illumina)

You can check which quality you are using with 
`testformat.sh in=sample.fastq.gz`

If you have old ilumina encoded quality values you can force the quality format by add the following line to the config.yaml

```
importqc_params: "iupacToN=t touppercase=t qout=33 addslash=t trimreaddescription=t qin=64"
```
If you have sanger quality values then use  `quin=33`at the end.

If you have short reads, e.g. 50nt you may also need to adopt the min_length parameter otherwise all your reads get filtered out.

**Comment by johanneswerner** [comment]
Thank you for your answer. 

Do you have an idea what might have gotten wrong here? I get the same output if I set `qin=64` or `qin=33`

```bash
for file in *.fastq.gz
do
  echo $file
  testformat.sh in=$file
  echo -en "\n"
done > out.txt 2>&1
```

[out.txt](https://github.com/metagenome-atlas/atlas/files/5821622/out.txt)

I checked that the data is complete (obtained from here: https://www.ebi.ac.uk/ena/browser/view/PRJNA438545 in case you want to reproduce my error). 

Thank you very much for your help.

**Comment by SilasK** [comment]
It's not your fault. There is something wrong with the N sequences downloaded. 

You have a majority of sanger sequences, so using qin=33 is the way to go.

What happens when you run atlas with the options:

```
importqc_params: "iupacToN=t touppercase=t qout=33 addslash=t trimreaddescription=t qin=33 tossbrokenreads"
```
You can also search for other options with reformat.sh that is used in this first init step.

Check how much you loose in the log file. If this doesn't work you might need to remove the problematic samples.

**Comment by johanneswerner** [comment]
problem solved, thank you very much. Can you explain to me what the problem was?

**Comment by SilasK** [comment]
I think the tool didn't understand  quality values corresponding to the NNN.
It seems the N's have high quality (F), wich doesn't make sense to me. 

Check how many reads were filtered out and maybe adappt the min_length. 

```
@SRR6853352.3 3/1
CCGCGGAGAGAGCAGATTCAAGGGTTTGCTGTCCAAGGANNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
+
BB/<BFFFFF<B<FFFFFFFFFFFBBFFFFBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFFFFFFBFFBBFFFFFFFFFF<<F<FFFFFF/FF/FFF#
```

Good lack with your atronaute bacteria.

**Comment by SilasK** [comment]
I just put this here. This argument would probably have solved the issue. `ignorebadquality=t`

**Comment by bcpd** [comment]
Hi all,

Re-opening the issue. Having successfuly installed atlas v. 2.9, I tested it on a test dataset, as follows:
```
git clone https://github.com/metagenome-atlas/example_data.git
atlas init --db-dir $databases --working-dir testrun --interleaved-fastq example_data/reads/test
atlas run all -w testrun -j 10
```
... And got the same "rule initialize_qc" error as above.

Thanks very much for your help solving this issue.

**Comment by SilasK** [comment]
Ok, in this case, the flag is necessary. In the new version of the example data I have the samples in non-interleaved files.
