### ISSUE TITLE
error in initialize_checkm 

### ISSUE THREAD

**Issue by SilasK** [metagenome-atlas/atlas#371]
This the initialize_checkm.log
```
Traceback (most recent call last):
  File "/mnt/gs18/scratch/users/choiyj/containers/atlas/databases/conda_envs/a7613bb5/bin/checkm", line 36, in <module>
    from checkm import main
ImportError: cannot import name 'main' from 'checkm' (unknown location)
```

This might be related to the new python versions

**Comment by SilasK** [comment]
> I just want to install Atlas as it is. The wrapper installation will be done by users if they want.
 I used 256 GB memory machine. Even though I shared memory with other users, I don’t think the memory is the issue.
I still do not know why I have errors for the test run.
Any idea?

Try to run atlas on a single machine

```
 atlas run all --jobs <N of cpu  on machine> --resources mem=256 
```

Assuming you can use all cpu/memory

**Comment by SilasK** [comment]
I still have an error message.
I used “atlas run all --jobs 20 --resources mem=120”
A log file is attached too.

Thanks!
```
 log: Genecatalog/subsets/genes/logs/subset1/eggNOG_homology_search_diamond.log (check log file(s) for error message)
    conda-env: /mnt/ufs18/rs-033/common-data/atlas/databases/conda_envs/23a1ada8
    shell:

        emapper.py -m diamond --no_annot --no_file_comments             --data_dir /mnt/ufs18/rs-033/common-data/atlas/databases/EggNOGV2 --cpu 8 -i Genecatalog/subsets/genes/subset1.faa             -o Genecatalog/subsets/genes/subset1 --override 2> Genecatalog/subsets/genes/logs/subset1/eggNOG_homology_search_diamond.log

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message
Shutting down, this might take some time.
```

Genecatalog/subsets/genes/logs/subset1/eggNOG_homology_search_diamond.log

```
diamond v2.0.7.145 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org

#CPU threads: 8
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: /mnt/ufs18/rs-033/common-data/atlas/.snakemake/shadow/tmpvlev5k4o/emappertmp_dmdn_Ftn_Kk
Opening the database...  [0.252s]
Percentage range of top alignment score to report hits: 3
Reference = /mnt/ufs18/rs-033/common-data/atlas/databases/EggNOGV2/eggnog_proteins.dmnd
Sequences = 21841973
Letters = 8413303269
Block size = 2000000000

... 

 File "/mnt/ufs18/rs-033/common-data/atlas/databases/conda_envs/23a1ada8/bin/emapper.py", line 1213, in <module>
    main(args)
  File "/mnt/ufs18/rs-033/common-data/atlas/databases/conda_envs/23a1ada8/bin/emapper.py", line 226, in main
    dump_diamond_matches(args.input, seed_orthologs_file, args)
  File "/mnt/ufs18/rs-033/common-data/atlas/databases/conda_envs/23a1ada8/bin/emapper.py", line 380, in dump_diamond_matches
    raise e
subprocess.CalledProcessError: Command '/mnt/ufs18/rs-033/common-data/atlas/databases/conda_envs/23a1ada8/bin/diamond blastp -d /mnt/ufs18/rs-033/common-data/atlas/databases/EggNOGV2/eggnog_proteins.dmnd -q /mnt/ufs18/rs-033/common-data/atlas/Genecatalog/subsets/genes/subset1.faa --more-sensitive --threads 8 -e 0.001000 -o /mnt/ufs18/rs-033/common-data/atlas/.snakemake/shadow/tmpvlev5k4o/emappertmp_dmdn_Ftn_Kk/34a6679896cf4854aa1bfb689524d0db --top 3 --query-cover 0 --subject-cover 0' returned non-zero exit status -9
```
