### ISSUE TITLE
Snakemake stuck at 'Downloading and installing remote packages.'

### ISSUE THREAD

**Issue by anitajnorman** [metagenome-atlas/atlas#390]
Hello

I've been trying to run Atlas on two different systems, one cluster and one linux server. In both cases, it gets stuck at 'Downloading and installing remote packages.' I've tried removing and reinstalling the atlas environment. I've tried installing each package in the dRep.yaml list independently with no issues. I've tried with both Conda and Mamba. None of these seems to prevent it from hanging. This is the command (linux) and stdout that it produces:

`(atlasenv) sh-4.3$ atlas run genomes --keep-going -j 70 --resources mem=700 --conda-frontend mamba --verbose
[2021-05-11 13:20 INFO] Executing: snakemake --snakefile /home/anita/.conda/envs/atlasenv/lib/python3.6/site-packages/atlas/Snakefile --directory /Datadrives/bulk1/anita/microbial/2008_30 --jobs 70 --rerun-incomplete --configfile '/Datadrives/bulk1/anita/microbial/2008_30/config.yaml' --nolock   --use-conda --conda-prefix /Datadrives/bulk1/anita/microbial/2008_30/databases/conda_envs   genomes  --keep-going --resources mem=700 --conda-frontend mamba --verbose
Building DAG of jobs...
Removing incomplete Conda environment /home/anita/.conda/envs/atlasenv/lib/python3.6/site-packages/atlas/rules/../envs/dRep.yaml...
Creating conda environment /home/anita/.conda/envs/atlasenv/lib/python3.6/site-packages/atlas/rules/../envs/dRep.yaml...
Downloading and installing remote packages.`

Any help or suggestions would be very much appreciated.

**Comment by ariahahn** [comment]
Having the same problem!

**Comment by luke-dt** [comment]
Same!

**Comment by SilasK** [comment]
I know this is a breaking issue since some time. I will look at this tomorrow. 

For now you can run all steps that don't require the dREP module. 
E.g. start with `atlas run  assembly`  or `atlas run binning`

**Comment by McGlock** [comment]
Having the same issues as above, tried running `atlas run assembly` and got the following error:

```
(atlasenv) ryan@leviathan:~/SeqData/Koonkie/Wagner_mats/atlas$ atlas run assembly
[2021-05-14 15:44 INFO] Executing: snakemake --snakefile /home/ryan/anaconda3/envs/atlasenv/lib/python3.6/site-packages/atlas/Snakefile --directory /media/hddd/SeqData/Koonkie/Wagner_mats/atlas  --rerun-incomplete --configfile '/media/hddd/SeqData/Koonkie/Wagner_mats/atlas/config.yaml' --nolock   --use-conda --conda-prefix /media/hddd/SeqData/Koonkie/Wagner_mats/atlas/databases/conda_envs   assembly   
Building DAG of jobs...
Creating conda environment /home/ryan/anaconda3/envs/atlasenv/lib/python3.6/site-packages/atlas/rules/../envs/prodigal.yaml...
Downloading and installing remote packages.
Environment for ../../../../../../home/ryan/anaconda3/envs/atlasenv/lib/python3.6/site-packages/atlas/envs/prodigal.yaml created (location: databases/conda_envs/5ddbcb1e)
Creating conda environment /home/ryan/anaconda3/envs/atlasenv/lib/python3.6/site-packages/atlas/rules/../envs/required_packages.yaml...
Downloading and installing remote packages.
Environment for ../../../../../../home/ryan/anaconda3/envs/atlasenv/lib/python3.6/site-packages/atlas/envs/required_packages.yaml created (location: databases/conda_envs/373d701f)
Creating conda environment /home/ryan/anaconda3/envs/atlasenv/lib/python3.6/site-packages/atlas/rules/../envs/assembly.yaml...
Downloading and installing remote packages.
Environment for ../../../../../../home/ryan/anaconda3/envs/atlasenv/lib/python3.6/site-packages/atlas/envs/assembly.yaml created (location: databases/conda_envs/b209bb98)
Creating conda environment /home/ryan/anaconda3/envs/atlasenv/lib/python3.6/site-packages/atlas/rules/../envs/report.yaml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /home/ryan/anaconda3/envs/atlasenv/lib/python3.6/site-packages/atlas/rules/../envs/report.yaml:
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

Downloading and Extracting Packages
jinja2-3.0.0         | 98 KB     | ########## | 100% 
ghostscript-9.54.0   | 57.0 MB   | ########## | 100% 
gitpython-3.1.17     | 115 KB    | ########## | 100% 
botocore-1.20.72     | 4.6 MB    | ########## | 100% 
glib-2.68.2          | 447 KB    | ########## | 100% 
glib-tools-2.68.2    | 86 KB     | ########## | 100% 
boto3-1.17.72        | 70 KB     | ########## | 100% 
configargparse-1.4.1 | 31 KB     | ########## | 100% 
dropbox-11.9.0       | 923 KB    | ########## | 100% 
markupsafe-2.0.0     | 22 KB     | ########## | 100% 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... 
done
Installing pip dependencies: ...working... Ran pip subprocess with arguments:
['/media/hddd/SeqData/Koonkie/Wagner_mats/atlas/databases/conda_envs/5e9f8273/bin/python', '-m', 'pip', 'install', '-U', '-r', '/media/hddd/SeqData/Koonkie/Wagner_mats/atlas/databases/conda_envs/condaenv.x03do0x3.requirements.txt']
Pip subprocess output:
Collecting cufflinks==0.12.1
  Using cached cufflinks-0.12.1-py3-none-any.whl
Collecting colorlover>=0.2
  Using cached colorlover-0.3.0-py3-none-any.whl (8.9 kB)
Requirement already satisfied: plotly>=2.0.0 in ./5e9f8273/lib/python3.6/site-packages (from cufflinks==0.12.1->-r /media/hddd/SeqData/Koonkie/Wagner_mats/atlas/databases/conda_envs/condaenv.x03do0x3.requirements.txt (line 1)) (2.2.2)
Requirement already satisfied: pandas in ./5e9f8273/lib/python3.6/site-packages (from cufflinks==0.12.1->-r /media/hddd/SeqData/Koonkie/Wagner_mats/atlas/databases/conda_envs/condaenv.x03do0x3.requirements.txt (line 1)) (0.20.3)
Requirement already satisfied: decorator>=4.0.6 in ./5e9f8273/lib/python3.6/site-packages (from plotly>=2.0.0->cufflinks==0.12.1->-r /media/hddd/SeqData/Koonkie/Wagner_mats/atlas/databases/conda_envs/condaenv.x03do0x3.requirements.txt (line 1)) (5.0.7)
Collecting nbformat>=4.2
  Using cached nbformat-5.1.3-py3-none-any.whl (178 kB)
Requirement already satisfied: pytz in ./5e9f8273/lib/python3.6/site-packages (from plotly>=2.0.0->cufflinks==0.12.1->-r /media/hddd/SeqData/Koonkie/Wagner_mats/atlas/databases/conda_envs/condaenv.x03do0x3.requirements.txt (line 1)) (2021.1)
Requirement already satisfied: requests in ./5e9f8273/lib/python3.6/site-packages (from plotly>=2.0.0->cufflinks==0.12.1->-r /media/hddd/SeqData/Koonkie/Wagner_mats/atlas/databases/conda_envs/condaenv.x03do0x3.requirements.txt (line 1)) (2.25.1)
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from plotly>=2.0.0->cufflinks==0.12.1->-r /media/hddd/SeqData/Koonkie/Wagner_mats/atlas/databases/conda_envs/condaenv.x03do0x3.requirements.txt (line 1)) (1.10.0)
Requirement already satisfied: traitlets>=4.1 in ./5e9f8273/lib/python3.6/site-packages (from nbformat>=4.2->plotly>=2.0.0->cufflinks==0.12.1->-r /media/hddd/SeqData/Koonkie/Wagner_mats/atlas/databases/conda_envs/condaenv.x03do0x3.requirements.txt (line 1)) (4.3.3)
Requirement already satisfied: ipython-genutils in ./5e9f8273/lib/python3.6/site-packages (from nbformat>=4.2->plotly>=2.0.0->cufflinks==0.12.1->-r /media/hddd/SeqData/Koonkie/Wagner_mats/atlas/databases/conda_envs/condaenv.x03do0x3.requirements.txt (line 1)) (0.2.0)
Collecting jupyter-core
  Using cached jupyter_core-4.7.1-py3-none-any.whl (82 kB)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in ./5e9f8273/lib/python3.6/site-packages (from nbformat>=4.2->plotly>=2.0.0->cufflinks==0.12.1->-r /media/hddd/SeqData/Koonkie/Wagner_mats/atlas/databases/conda_envs/condaenv.x03do0x3.requirements.txt (line 1)) (3.2.0)
Requirement already satisfied: pyrsistent>=0.14.0 in ./5e9f8273/lib/python3.6/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2->plotly>=2.0.0->cufflinks==0.12.1->-r /media/hddd/SeqData/Koonkie/Wagner_mats/atlas/databases/conda_envs/condaenv.x03do0x3.requirements.txt (line 1)) (0.17.3)
Requirement already satisfied: attrs>=17.4.0 in ./5e9f8273/lib/python3.6/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2->plotly>=2.0.0->cufflinks==0.12.1->-r /media/hddd/SeqData/Koonkie/Wagner_mats/atlas/databases/conda_envs/condaenv.x03do0x3.requirements.txt (line 1)) (21.2.0)
Requirement already satisfied: setuptools in /usr/local/lib/python2.7/dist-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2->plotly>=2.0.0->cufflinks==0.12.1->-r /media/hddd/SeqData/Koonkie/Wagner_mats/atlas/databases/conda_envs/condaenv.x03do0x3.requirements.txt (line 1)) (34.4.1)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: importlib-metadata in ./5e9f8273/lib/python3.6/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2->plotly>=2.0.0->cufflinks==0.12.1->-r /media/hddd/SeqData/Koonkie/Wagner_mats/atlas/databases/conda_envs/condaenv.x03do0x3.requirements.txt (line 1)) (4.0.1)
Requirement already satisfied: zipp>=0.5 in ./5e9f8273/lib/python3.6/site-packages (from importlib-metadata->jsonschema!=2.5.0,>=2.4->nbformat>=4.2->plotly>=2.0.0->cufflinks==0.12.1->-r /media/hddd/SeqData/Koonkie/Wagner_mats/atlas/databases/conda_envs/condaenv.x03do0x3.requirements.txt (line 1)) (3.4.1)
Requirement already satisfied: typing-extensions>=3.6.4 in ./5e9f8273/lib/python3.6/site-packages (from importlib-metadata->jsonschema!=2.5.0,>=2.4->nbformat>=4.2->plotly>=2.0.0->cufflinks==0.12.1->-r /media/hddd/SeqData/Koonkie/Wagner_mats/atlas/databases/conda_envs/condaenv.x03do0x3.requirements.txt (line 1)) (3.7.4.3)
Requirement already satisfied: python-dateutil>=2 in ./5e9f8273/lib/python3.6/site-packages (from pandas->cufflinks==0.12.1->-r /media/hddd/SeqData/Koonkie/Wagner_mats/atlas/databases/conda_envs/condaenv.x03do0x3.requirements.txt (line 1)) (2.8.1)
Requirement already satisfied: numpy>=1.7.0 in ./5e9f8273/lib/python3.6/site-packages (from pandas->cufflinks==0.12.1->-r /media/hddd/SeqData/Koonkie/Wagner_mats/atlas/databases/conda_envs/condaenv.x03do0x3.requirements.txt (line 1)) (1.13.1)
Requirement already satisfied: idna<3,>=2.5 in ./5e9f8273/lib/python3.6/site-packages (from requests->plotly>=2.0.0->cufflinks==0.12.1->-r /media/hddd/SeqData/Koonkie/Wagner_mats/atlas/databases/conda_envs/condaenv.x03do0x3.requirements.txt (line 1)) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in ./5e9f8273/lib/python3.6/site-packages (from requests->plotly>=2.0.0->cufflinks==0.12.1->-r /media/hddd/SeqData/Koonkie/Wagner_mats/atlas/databases/conda_envs/condaenv.x03do0x3.requirements.txt (line 1)) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in ./5e9f8273/lib/python3.6/site-packages (from requests->plotly>=2.0.0->cufflinks==0.12.1->-r /media/hddd/SeqData/Koonkie/Wagner_mats/atlas/databases/conda_envs/condaenv.x03do0x3.requirements.txt (line 1)) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./5e9f8273/lib/python3.6/site-packages (from requests->plotly>=2.0.0->cufflinks==0.12.1->-r /media/hddd/SeqData/Koonkie/Wagner_mats/atlas/databases/conda_envs/condaenv.x03do0x3.requirements.txt (line 1)) (1.26.4)
Requirement already satisfied: appdirs>=1.4.0 in /usr/local/lib/python2.7/dist-packages (from setuptools->jsonschema!=2.5.0,>=2.4->nbformat>=4.2->plotly>=2.0.0->cufflinks==0.12.1->-r /media/hddd/SeqData/Koonkie/Wagner_mats/atlas/databases/conda_envs/condaenv.x03do0x3.requirements.txt (line 1)) (1.4.3)
Requirement already satisfied: packaging>=16.8 in /usr/local/lib/python2.7/dist-packages (from setuptools->jsonschema!=2.5.0,>=2.4->nbformat>=4.2->plotly>=2.0.0->cufflinks==0.12.1->-r /media/hddd/SeqData/Koonkie/Wagner_mats/atlas/databases/conda_envs/condaenv.x03do0x3.requirements.txt (line 1)) (16.8)
Requirement already satisfied: pyparsing in /usr/local/lib/python2.7/dist-packages (from packaging>=16.8->setuptools->jsonschema!=2.5.0,>=2.4->nbformat>=4.2->plotly>=2.0.0->cufflinks==0.12.1->-r /media/hddd/SeqData/Koonkie/Wagner_mats/atlas/databases/conda_envs/condaenv.x03do0x3.requirements.txt (line 1)) (2.2.0)
Installing collected packages: six, jupyter-core, nbformat, colorlover, cufflinks
  Attempting uninstall: six
    Found existing installation: six 1.10.0
    Uninstalling six-1.10.0:

failed
Pip subprocess error:
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'DESCRIPTION.rst'
Consider using the `--user` option or check the permissions.



CondaEnvException: Pip failed


[2021-05-14 18:08 CRITICAL] Command 'snakemake --snakefile /home/ryan/anaconda3/envs/atlasenv/lib/python3.6/site-packages/atlas/Snakefile --directory /media/hddd/SeqData/Koonkie/Wagner_mats/atlas  --rerun-incomplete --configfile '/media/hddd/SeqData/Koonkie/Wagner_mats/atlas/config.yaml' --nolock   --use-conda --conda-prefix /media/hddd/SeqData/Koonkie/Wagner_mats/atlas/databases/conda_envs   assembly   ' returned non-zero exit status 1.
```

**Comment by SilasK** [comment]
I hope this should fix this issue.

https://github.com/metagenome-atlas/atlas/releases/tag/2.6a1

**Comment by McGlock** [comment]
@SilasK 
Hey thanks for working on this!
I pulled down the source you released and installed with the following from your "Getting Started"
```
git clone https://github.com/metagenome-atlas/atlas.git
cd atlas

# optional change to different branch
# git checkout branchname

# create dependencies for atlas
mamba env create -n atlas-dev --file atlasenv.yml
conda activate atlas-dev

# install atlas version. Changes in this files are directly available in the atlas dev version
pip install --editable .
cd ..
```
I then ran the test data via:
```
wget https://zenodo.org/record/3992790/files/test_reads.tar.gz
tar -xzf test_reads.tar.gz
atlas init --db-dir databases test_reads
```
Then lastly:
```
atlas run all --cores all
```
And I got this output resulting in an error:
```
(atlas-dev) ryan@leviathan:~/SeqData/Koonkie/Wagner_mats/atlas$ atlas run all --cores all
[2021-05-16 08:25 INFO] Executing: snakemake --snakefile /home/ryan/Dev/atlas-2.6a1/atlas/Snakefile --directory /media/hddd/SeqData/Koonkie/Wagner_mats/atlas  --rerun-incomplete --configfile '/media/hddd/SeqData/Koonkie/Wagner_mats/atlas/config.yaml' --nolock   --use-conda --conda-prefix /media/hddd/SeqData/Koonkie/Wagner_mats/atlas/databases/conda_envs   --scheduler greedy  all  --cores all 
Traceback (most recent call last):
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/snakemake/__init__.py", line 594, in snakemake
    snakefile, overwrite_first_rule=True, print_compilation=print_compilation
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/snakemake/workflow.py", line 1094, in include
    if is_local_file(snakefile):
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/snakemake/common.py", line 65, in is_local_file
    from smart_open import parse_uri
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/smart_open/__init__.py", line 34, in <module>
    from .smart_open_lib import open, parse_uri, smart_open, register_compressor  # noqa: E402
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/smart_open/smart_open_lib.py", line 35, in <module>
    from smart_open import doctools
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/smart_open/doctools.py", line 21, in <module>
    from . import transport
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/smart_open/transport.py", line 97, in <module>
    register_transport('smart_open.azure')
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/smart_open/transport.py", line 49, in register_transport
    submodule = importlib.import_module(submodule)
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/smart_open/azure.py", line 19, in <module>
    import azure.storage.blob
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/azure/storage/blob/__init__.py", line 10, in <module>
    from ._blob_client import BlobClient
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/azure/storage/blob/_blob_client.py", line 26, in <module>
    from ._shared.base_client import StorageAccountHostsMixin, parse_connection_str, parse_query, TransportWrapper
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/azure/storage/blob/_shared/base_client.py", line 38, in <module>
    from .constants import STORAGE_OAUTH_SCOPE, SERVICE_HOST_BASE, CONNECTION_TIMEOUT, READ_TIMEOUT
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/azure/storage/blob/_shared/constants.py", line 8, in <module>
    from .._generated import AzureBlobStorage
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/azure/storage/blob/_generated/__init__.py", line 9, in <module>
    from ._azure_blob_storage import AzureBlobStorage
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/azure/storage/blob/_generated/_azure_blob_storage.py", line 19, in <module>
    from .operations import ServiceOperations
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/azure/storage/blob/_generated/operations/__init__.py", line 9, in <module>
    from ._service_operations import ServiceOperations
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/azure/storage/blob/_generated/operations/_service_operations.py", line 15, in <module>
    from .. import models as _models
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/azure/storage/blob/_generated/models/__init__.py", line 10, in <module>
    from ._models_py3 import AccessPolicy
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/azure/storage/blob/_generated/models/_models_py3.py", line 15, in <module>
    from ._azure_blob_storage_enums import *
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/azure/storage/blob/_generated/models/_azure_blob_storage_enums.py", line 29, in <module>
    class AccessTier(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/enum.py", line 135, in __prepare__
    member_type, first_enum = metacls._get_mixins_(bases)
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/enum.py", line 472, in _get_mixins_
    raise TypeError("new enumerations should be created as "
TypeError: new enumerations should be created as `EnumName([mixin_type, ...] [data_type,] enum_type)`
[2021-05-16 08:26 CRITICAL] Command 'snakemake --snakefile /home/ryan/Dev/atlas-2.6a1/atlas/Snakefile --directory /media/hddd/SeqData/Koonkie/Wagner_mats/atlas  --rerun-incomplete --configfile '/media/hddd/SeqData/Koonkie/Wagner_mats/atlas/config.yaml' --nolock   --use-conda --conda-prefix /media/hddd/SeqData/Koonkie/Wagner_mats/atlas/databases/conda_envs   --scheduler greedy  all  --cores all ' returned non-zero exit status 1.
```
I also range `atlas run assembly --cores all` as well as `atlas run all --resources mem=100 --jobs 10` and got the same error message.
I appologize, but I'm not familar enough with snakemake to understand what the issue is or if there is possible something I'm not doing that is causing this problem. I appreciate your help!
Thank you!

**Comment by SilasK** [comment]
I don't understand the snakemake error either. 
Could you check if you have snakemake v >6.1

Maybe the --cores all is strange try --cores with an int

**Comment by McGlock** [comment]
I'm using snakemake v6.3.0
```
(atlas-dev) ryan@leviathan:~$ snakemake -v
6.3.0
```
I have also tried specifying an int there with the same results.
```
(atlas-dev) ryan@leviathan:~/SeqData/Koonkie/Wagner_mats/atlas$ atlas run all --cores 10
[2021-05-16 15:21 INFO] Executing: snakemake --snakefile /home/ryan/Dev/atlas-2.6a1/atlas/Snakefile --directory /media/hddd/SeqData/Koonkie/Wagner_mats/atlas  --rerun-incomplete --configfile '/media/hddd/SeqData/Koonkie/Wagner_mats/atlas/config.yaml' --nolock   --use-conda --conda-prefix /media/hddd/SeqData/Koonkie/Wagner_mats/atlas/databases/conda_envs   --scheduler greedy  all  --cores 10 
Traceback (most recent call last):
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/snakemake/__init__.py", line 594, in snakemake
    snakefile, overwrite_first_rule=True, print_compilation=print_compilation
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/snakemake/workflow.py", line 1094, in include
    if is_local_file(snakefile):
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/snakemake/common.py", line 65, in is_local_file
    from smart_open import parse_uri
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/smart_open/__init__.py", line 34, in <module>
    from .smart_open_lib import open, parse_uri, smart_open, register_compressor  # noqa: E402
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/smart_open/smart_open_lib.py", line 35, in <module>
    from smart_open import doctools
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/smart_open/doctools.py", line 21, in <module>
    from . import transport
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/smart_open/transport.py", line 97, in <module>
    register_transport('smart_open.azure')
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/smart_open/transport.py", line 49, in register_transport
    submodule = importlib.import_module(submodule)
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/smart_open/azure.py", line 19, in <module>
    import azure.storage.blob
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/azure/storage/blob/__init__.py", line 10, in <module>
    from ._blob_client import BlobClient
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/azure/storage/blob/_blob_client.py", line 26, in <module>
    from ._shared.base_client import StorageAccountHostsMixin, parse_connection_str, parse_query, TransportWrapper
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/azure/storage/blob/_shared/base_client.py", line 38, in <module>
    from .constants import STORAGE_OAUTH_SCOPE, SERVICE_HOST_BASE, CONNECTION_TIMEOUT, READ_TIMEOUT
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/azure/storage/blob/_shared/constants.py", line 8, in <module>
    from .._generated import AzureBlobStorage
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/azure/storage/blob/_generated/__init__.py", line 9, in <module>
    from ._azure_blob_storage import AzureBlobStorage
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/azure/storage/blob/_generated/_azure_blob_storage.py", line 19, in <module>
    from .operations import ServiceOperations
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/azure/storage/blob/_generated/operations/__init__.py", line 9, in <module>
    from ._service_operations import ServiceOperations
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/azure/storage/blob/_generated/operations/_service_operations.py", line 15, in <module>
    from .. import models as _models
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/azure/storage/blob/_generated/models/__init__.py", line 10, in <module>
    from ._models_py3 import AccessPolicy
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/azure/storage/blob/_generated/models/_models_py3.py", line 15, in <module>
    from ._azure_blob_storage_enums import *
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/site-packages/azure/storage/blob/_generated/models/_azure_blob_storage_enums.py", line 29, in <module>
    class AccessTier(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/enum.py", line 135, in __prepare__
    member_type, first_enum = metacls._get_mixins_(bases)
  File "/home/ryan/anaconda3/envs/atlas-dev/lib/python3.7/enum.py", line 472, in _get_mixins_
    raise TypeError("new enumerations should be created as "
TypeError: new enumerations should be created as `EnumName([mixin_type, ...] [data_type,] enum_type)`
[2021-05-16 15:21 CRITICAL] Command 'snakemake --snakefile /home/ryan/Dev/atlas-2.6a1/atlas/Snakefile --directory /media/hddd/SeqData/Koonkie/Wagner_mats/atlas  --rerun-incomplete --configfile '/media/hddd/SeqData/Koonkie/Wagner_mats/atlas/config.yaml' --nolock   --use-conda --conda-prefix /media/hddd/SeqData/Koonkie/Wagner_mats/atlas/databases/conda_envs   --scheduler greedy  all  --cores 10 ' returned non-zero exit status 1.
```

**Comment by luke-dt** [comment]
I installed 2.6a1, and re-ran `atlas run all` on the test dataset. After 18 hrs, it's still at this step:

`Creating conda environment /opt/apps/labs/gdlab/envs/metagenome-atlas/2.6a1/lib/python3.6/site-packages/atlas/rules/../envs/dRep.yaml...
Downloading and installing remote packages.`

**Comment by SilasK** [comment]
@luke-dt I could re-install drep overnight but I don't know exact how long it took. Do you want to try if #394 solves the problem.

**Comment by luke-dt** [comment]
I tried that solution, but had to edit dRep.yaml a little more to get it running without an error while solving the environment. It's running now, although I'm having a new issue (see #395)

```
channels:
    - conda-forge
    - bioconda
    - ruby-lang
    - defaults
dependencies:
    - python=3.6
    - mummer>=3.22
    - mash>=2
    - prodigal=2.6.3
    - fastani=1.32
    - drep=3.2.0
```

**Comment by anitajnorman** [comment]
@SilasK Thanks for looking into this issue. Unfortunately, I am still running into the same problem. I am running v2.6a1 and it is getting stuck at Downloading and installing remote packages on the dRep.yaml:

```
channels:
    - conda-forge
    - bioconda
    - ruby-lang
    - defaults
dependencies:
    - python=3.6
    - mummer>=3.22
    - mash>=2
    - prodigal=2.6.3
    - pip:
      - drep==2.2.2
```

@luke-dt in your dRep.yaml, did it look like above before you made the changes?

**Comment by SilasK** [comment]
@anitajnorman Solution is implemented on a branch of atlas not yet in the conda version.

**Comment by SilasK** [comment]
An intermediate solution is always to run 

`atlas run binning` This does all the assembly and binning but not the dREP.

**Comment by SilasK** [comment]
I simplidfied the drep in v2.6a2 I hope this solves most of this issues

**Comment by crusher083** [comment]
I have the same issue, used `atlas run all` in the last dev version and 
`Downloading packages` is running for 10 hours already. I wonder if that could be considered stuck or is this normal runtime?
