### ISSUE TITLE
Key Error during dereplication

### ISSUE THREAD

**Issue by luke-dt** [metagenome-atlas/atlas#395]
I'm running 2.6a1 on the test dataset with dRep 3.2, and atlas quits with an error during `dRep dereplicate`. Below is the error from `logs/genomes/pre_dereplication.log`:

```
***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************
    
Will filter the genome list
5 genomes were input to dRep
Calculating genome info of genomes
100.00% of genomes passed length filtering
100.00% of genomes passed checkM filtering
***************************************************
    ..:: dRep dereplicate Step 2. Cluster ::..
***************************************************
    
Running primary clustering
Running pair-wise MASH clustering
3 primary clusters made
Running secondary clustering
3. Nevermind! Skipping secondary clustering
Step 4. Return output
***************************************************
    ..:: dRep dereplicate Step 3. Choose ::..
***************************************************
    
Loading work directory
Traceback (most recent call last):
  File "/scratch/ref/gdlab/metagenome-atlas_db/2.6a1/conda_envs/85ea1ba518acc8559abd39ebd8927742/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'reference'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/ref/gdlab/metagenome-atlas_db/2.6a1/conda_envs/85ea1ba518acc8559abd39ebd8927742/bin/dRep", line 32, in <module>
    Controller().parseArguments(args)
  File "/scratch/ref/gdlab/metagenome-atlas_db/2.6a1/conda_envs/85ea1ba518acc8559abd39ebd8927742/lib/python3.6/site-packages/drep/controller.py", line 100, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/scratch/ref/gdlab/metagenome-atlas_db/2.6a1/conda_envs/85ea1ba518acc8559abd39ebd8927742/lib/python3.6/site-packages/drep/controller.py", line 48, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/scratch/ref/gdlab/metagenome-atlas_db/2.6a1/conda_envs/85ea1ba518acc8559abd39ebd8927742/lib/python3.6/site-packages/drep/d_workflows.py", line 45, in dereplicate_wrapper
    drep.d_choose.d_choose_wrapper(wd, **kwargs)
  File "/scratch/ref/gdlab/metagenome-atlas_db/2.6a1/conda_envs/85ea1ba518acc8559abd39ebd8927742/lib/python3.6/site-packages/drep/d_choose.py", line 72, in d_choose_wrapper
    Gdb = add_centrality(wd, Gdb, **kwargs)
  File "/scratch/ref/gdlab/metagenome-atlas_db/2.6a1/conda_envs/85ea1ba518acc8559abd39ebd8927742/lib/python3.6/site-packages/drep/d_choose.py", line 306, in add_centrality
    Ndb['cluster_1'] = Ndb['reference'].map(g2c)
  File "/scratch/ref/gdlab/metagenome-atlas_db/2.6a1/conda_envs/85ea1ba518acc8559abd39ebd8927742/lib/python3.6/site-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/scratch/ref/gdlab/metagenome-atlas_db/2.6a1/conda_envs/85ea1ba518acc8559abd39ebd8927742/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'reference'
```

**Comment by SilasK** [comment]
Maybe it's due to the fact that we skip the secondary clustering..

I simplified the dereplication maybe you want to try again.

I also asked the question at https://github.com/MrOlm/drep/issues/120

**Comment by SilasK** [comment]
according to the author of drep my change should solve the problem.

**Comment by luke-dt** [comment]
confirming that this fixes the error with dRep, but now I'm having an issue with eggnog (see #398)
