### ISSUE TITLE
Atlas rerun error with v. 2.6a2

### ISSUE THREAD

**Issue by johanneswerner** [metagenome-atlas/atlas#398]
My previous atlas run aborted in-between (probably with some inconsistencies of the eggnog db). 

Reinitializing the databases and rerunning with atlas v. 2.6a2 leads to a weird behavior. 

```bash
$ atlas run
[2021-05-31 08:57 INFO] Executing: snakemake --snakefile /home/ubuntu/miniconda3/envs/atlas_new/lib/python3.7/site-packages/atlas/Snakefile --directory /data_iow/PBS_NS/atlas_run  --rerun-incomplete --configfile '/data_iow/PBS_NS/atlas_run/config.yaml' --nolock   --use-conda --conda-prefix /data_iow/db_atlas/conda_envs   --scheduler greedy  all   
Error: you need to specify the maximum number of CPU cores to be used at the same time. If you want to use N cores, say --cores N or -jN. For all cores on your system (be sure that this is appropriate) use --cores all. For no parallelization use --cores 1 or -j1.
[2021-05-31 08:57 CRITICAL] Command 'snakemake --snakefile /home/ubuntu/miniconda3/envs/atlas_new/lib/python3.7/site-packages/atlas/Snakefile --directory /data_iow/PBS_NS/atlas_run  --rerun-incomplete --configfile '/data_iow/PBS_NS/atlas_run/config.yaml' --nolock   --use-conda --conda-prefix /data_iow/db_atlas/conda_envs   --scheduler greedy  all   ' returned non-zero exit status 1.
 ```

`atlas run` does not seem to produce any parameter for the `--cores` parameter for `snakemake` - at least this is what I assume. 

Adding the numbers of cores (in my case 36) manually leads to another error that I do not understand, some help would be wonderful: 

```bash
$ atlas run -j 36

# (...)
[Mon May 31 08:58:43 2021]
localrule combine_egg_nogg_annotations:
    input: Genecatalog/subsets/genes/subset1.emapper.annotations
    output: Genecatalog/annotations/eggNog.tsv.gz
    jobid: 1240
    resources: mem=60, time=5

localrules directive specifies rules that are not present in the Snakefile:
        verify_eggNOG_files

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/atlas_new/lib/python3.7/site-packages/snakemake/__init__.py", line 785, in snakemake
    keepmetadata=keep_metadata,
  File "/home/ubuntu/miniconda3/envs/atlas_new/lib/python3.7/site-packages/snakemake/workflow.py", line 731, in execute
    dag.update_checkpoint_dependencies()
  File "/home/ubuntu/miniconda3/envs/atlas_new/lib/python3.7/site-packages/snakemake/dag.py", line 1312, in update_checkpoint_dependencies
    self.postprocess()
  File "/home/ubuntu/miniconda3/envs/atlas_new/lib/python3.7/site-packages/snakemake/dag.py", line 1193, in postprocess
    self.cleanup()
  File "/home/ubuntu/miniconda3/envs/atlas_new/lib/python3.7/site-packages/snakemake/dag.py", line 258, in cleanup
    del self.depending[dep][job]
KeyError: passtrough_se_merged
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Note the path to the log file for debugging.
Documentation is available at: https://metagenome-atlas.readthedocs.io
Issues can be raised at: https://github.com/metagenome-atlas/atlas/issues
Complete log: /data_iow/PBS_NS/atlas_run/.snakemake/log/2021-05-31T085837.424945.snakemake.log
[2021-05-31 08:58 CRITICAL] Command 'snakemake --snakefile /home/ubuntu/miniconda3/envs/atlas_new/lib/python3.7/site-packages/atlas/Snakefile --directory /data_iow/PBS_NS/atlas_run --jobs 36 --rerun-incomplete --configfile '/data_iow/PBS_NS/atlas_run/config.yaml' --nolock   --use-conda --conda-prefix /data_iow/db_atlas/conda_envs   --scheduler greedy  all   ' returned non-zero exit status 1.
```

The log file does not contain the `KeyError` mentioned above.

Any ideas what goes wrong here? Thank you very much for your help.

**Comment by luke-dt** [comment]
I'm having a similar issue with 2.6a2 which appears to be related to eggnog when using the test read set. I can't find the log file related to eggnog, but here's the tail of the std out:

```
(...)
[Wed Jun  2 03:57:28 2021]
rule eggNOG_annotation:
    input: /scratch/ref/gdlab/metagenome-atlas_db/2.6a2/EggNOG_V5/eggnog.db, /scratch/ref/gdlab/metagenome-atlas_db/2.6a2/EggNOG_V5/eggnog_proteins.dmnd, Genecatalog/subsets/genes/subset1.emapper.seed_orthologs
    output: Genecatalog/subsets/genes/subset1.emapper.annotations
    log: Genecatalog/subsets/genes/logs/subset1/eggNOG_annotate_hits_table.log
    jobid: 145
    wildcards: folder=Genecatalog/subsets/genes, prefix=subset1
    threads: 8
    resources: mem=20, time=5

localrules directive specifies rules that are not present in the Snakefile:
	verify_eggNOG_files

Job counts:
	count	jobs
	1	eggNOG_annotation
	1
Assuming -m no_search
#  emapper-2.1.2
# emapper.py  --annotate_hits_table Genecatalog/subsets/genes/subset1.emapper.seed_orthologs --no_file_comments --override -o Genecatalog/subsets/genes/subset1 --cpu 8 --data_dir /scratch/ref/gdlab/metagenome-atlas_db/2.6a2/EggNOG_V5
Done
   /scratch/gdlab/ldioriot/atlas_test/2.6a2/.snakemake/shadow/tmpcwreiyn7/Genecatalog/subsets/genes/subset1.emapper.annotations

================================================================================
CITATION:
If you use this software, please cite:

[1] Fast genome-wide functional annotation through orthology assignment by
      eggNOG-mapper. Jaime Huerta-Cepas, Kristoffer Forslund, Luis Pedro Coelho,
      Damian Szklarczyk, Lars Juhl Jensen, Christian von Mering and Peer Bork.
      Mol Biol Evol (2017). doi: https://doi.org/10.1093/molbev/msx148

[2] eggNOG 5.0: a hierarchical, functionally and phylogenetically annotated
      orthology resource based on 5090 organisms and 2502 viruses. Jaime
      Huerta-Cepas, Damian Szklarczyk, Davide Heller, Ana Hernandez-Plaza,
      Sofia K Forslund, Helen Cook, Daniel R Mende, Ivica Letunic, Thomas
      Rattei, Lars J Jensen, Christian von Mering and Peer Bork. Nucleic Acids
      Research, Volume 47, Issue D1, 8 January 2019, Pages D309-D314,
      https://doi.org/10.1093/nar/gky1085 
e.g. Functional annotation was performed using emapper-2.1.2 [1]
 based on eggNOG orthology data [2]. Sequence searches were performed using [3].


================================================================================

Total hits processed: 3867
Total time: 1620 secs
FINISHED
Removing temporary output file Genecatalog/subsets/genes/subset1.emapper.seed_orthologs.
[Wed Jun  2 04:24:36 2021]
Finished job 145.
147 of 152 steps (97%) done

[Wed Jun  2 04:24:36 2021]
localrule combine_egg_nogg_annotations:
    input: Genecatalog/subsets/genes/subset1.emapper.annotations
    output: Genecatalog/annotations/eggNog.tsv.gz
    jobid: 140
    resources: mem=60, time=5

localrules directive specifies rules that are not present in the Snakefile:
	verify_eggNOG_files

Traceback (most recent call last):
  File "/opt/apps/labs/gdlab/envs/metagenome-atlas/2.6a2/lib/python3.6/site-packages/snakemake/__init__.py", line 785, in snakemake
    keepmetadata=keep_metadata,
  File "/opt/apps/labs/gdlab/envs/metagenome-atlas/2.6a2/lib/python3.6/site-packages/snakemake/workflow.py", line 731, in execute
    dag.update_checkpoint_dependencies()
  File "/opt/apps/labs/gdlab/envs/metagenome-atlas/2.6a2/lib/python3.6/site-packages/snakemake/dag.py", line 1312, in update_checkpoint_dependencies
    self.postprocess()
  File "/opt/apps/labs/gdlab/envs/metagenome-atlas/2.6a2/lib/python3.6/site-packages/snakemake/dag.py", line 1193, in postprocess
    self.cleanup()
  File "/opt/apps/labs/gdlab/envs/metagenome-atlas/2.6a2/lib/python3.6/site-packages/snakemake/dag.py", line 258, in cleanup
    del self.depending[dep][job]
KeyError: passtrough_se_merged
[Wed Jun  2 04:30:28 2021]
Finished job 131.
148 of 152 steps (97%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /scratch/gdlab/ldioriot/atlas_test/2.6a2/.snakemake/log/2021-06-01T232123.777770.snakemake.log
Note the path to the log file for debugging.
Documentation is available at: https://metagenome-atlas.readthedocs.io
Issues can be raised at: https://github.com/metagenome-atlas/atlas/issues
[2021-06-02 04:30 CRITICAL] Command 'snakemake --snakefile /opt/apps/labs/gdlab/envs/metagenome-atlas/2.6a2/lib/python3.6/site-packages/atlas/Snakefile --directory /scratch/gdlab/ldioriot/atlas_test/2.6a2 --jobs 24 --rerun-incomplete --configfile '/scratch/gdlab/ldioriot/atlas_test/2.6a2/config.yaml' --nolock   --use-conda --conda-prefix /scratch/ref/gdlab/metagenome-atlas_db/2.6a2/conda_envs   --scheduler greedy  all  --resources mem=250 ' returned non-zero exit status 1.

real	309m7.076s
user	450m48.400s
sys	50m4.123s
+ RC=1
+ set +x
Error Occured!
```

**Comment by SilasK** [comment]
Seems that snakemake tries to update the DAG and goes way back to rules related to assembly. Did you start with a previous version and then update to the latest atlas version?

Couls you send me the relatively long stdout of your command with the additional argument --debug-dag

**Comment by rustycat17** [comment]
> Did you start with a previous version and then update to the latest atlas version?

Yes, that is what I did (I hoped to fix the eggnog-related error). 

> Couls you send me the relatively long stdout of your command with the additional argument --debug-dag

Attached: 
[2021-06-04T223613.812437.snakemake.log](https://github.com/metagenome-atlas/atlas/files/6601131/2021-06-04T223613.812437.snakemake.log)


Btw: 

I get this also with a complete rerun of the dataset (in #400, I am mentioning this here, because I assume that this is related):  

```
localrules directive specifies rules that are not present in the Snakefile:
        verify_eggNOG_files
...
```

Thank you for your help.

**Comment by johanneswerner** [comment]
> Did you start with a previous version and then update to the latest atlas version?

Yes, that is what I did (I hoped to fix the eggnog-related error). 

> Couls you send me the relatively long stdout of your command with the additional argument --debug-dag

Attached: 
[2021-06-04T223613.812437.snakemake.log](https://github.com/metagenome-atlas/atlas/files/6601131/2021-06-04T223613.812437.snakemake.log)


Btw: 

I get this also with a complete rerun of the dataset (in #400, I am mentioning this here, because I assume that this is related):  

```
localrules directive specifies rules that are not present in the Snakefile:
        verify_eggNOG_files
...
```

Thank you for your help (edit: sorry was logged in under a different github username).

**Comment by SilasK** [comment]
The warning about verify_eggNOG_files isn't related to the error I alos fixed it in the last commit. 

In order to keep things organized I continue writing on #401
