### ISSUE TITLE
Error on branch normalize again

### ISSUE THREAD

**Issue by makrez** [metagenome-atlas/atlas#404]
I am using the atlas-dev version and I followed the installation as explained here; #375 

I encountered a few errors:

The first one was similar to #401, which I solved by downgrading snakemake to 6.3

The second error was that the download and installation step got stuck as discussed in #390. In the meantime, I just ran `atlas run assemble` before trying to solve the download/installation issue.

The error I would like to report occurs when running the rule apply_quality_filter:

This is the log from `{sample}/logs/QC/quality_filter.log:

```
ava -Djava.library.path=/data/projects/p532_BX-rhizosphere-metagenomics/metagenome-atlas/atlas/databases/conda_envs/5fdd92e4b36ace4d6b33e8262734fe1d/opt/bbmap-37.99/jni/ -ea -Xmx51G -Xms51G -cp /data/projects/p532_BX-rhizosphere-metagenomics/metagenome-atlas/atlas/databases/conda_envs/5fdd92e4b36ace4d6b33e8262734fe1d/opt/bbmap-37.99/current/ jgi.BBDukF in1=SG-bx-4/sequence_quality_control/SG-bx-4_deduplicated_R1.fastq.gz in2=SG-bx-4/sequence_quality_control/SG-bx-4_deduplicated_R2.fastq.gz ref=/data/projects/p532_BX-rhizosphere-metagenomics/metagenome-atlas/atlas/databases/adapters.fa interleaved=f out=SG-bx-4/sequence_quality_control/SG-bx-4_filtered_R1.fastq.gz out2=SG-bx-4/sequence_quality_control/SG-bx-4_filtered_R2.fastq.gz outs=SG-bx-4/logs/SG-bx-4_quality_filtering_stats.txt stats=SG-bx-4/logs/SG-bx-4_quality_filtering_stats.txt overwrite=true qout=33 trd=t hdist=1 k=27 ktrim=r mink=8 trimq=10 qtrim=rl threads=8 minlength=51 maxns=-1 minbasefrequency=0.05 ecco=t prealloc=t -Xmx51G
Executing jgi.BBDukF [in1=SG-bx-4/sequence_quality_control/SG-bx-4_deduplicated_R1.fastq.gz, in2=SG-bx-4/sequence_quality_control/SG-bx-4_deduplicated_R2.fastq.gz, ref=/data/projects/p532_BX-rhizosphere-metagenomics/metagenome-atlas/atlas/databases/adapters.fa, interleaved=f, out=SG-bx-4/sequence_quality_control/SG-bx-4_filtered_R1.fastq.gz, out2=SG-bx-4/sequence_quality_control/SG-bx-4_filtered_R2.fastq.gz, outs=SG-bx-4/logs/SG-bx-4_quality_filtering_stats.txt, stats=SG-bx-4/logs/SG-bx-4_quality_filtering_stats.txt, overwrite=true, qout=33, trd=t, hdist=1, k=27, ktrim=r, mink=8, trimq=10, qtrim=rl, threads=8, minlength=51, maxns=-1, minbasefrequency=0.05, ecco=t, prealloc=t, -Xmx51G]
Version 37.99 [in1=SG-bx-4/sequence_quality_control/SG-bx-4_deduplicated_R1.fastq.gz, in2=SG-bx-4/sequence_quality_control/SG-bx-4_deduplicated_R2.fastq.gz, ref=/data/projects/p532_BX-rhizosphere-metagenomics/metagenome-atlas/atlas/databases/adapters.fa, interleaved=f, out=SG-bx-4/sequence_quality_control/SG-bx-4_filtered_R1.fastq.gz, out2=SG-bx-4/sequence_quality_control/SG-bx-4_filtered_R2.fastq.gz, outs=SG-bx-4/logs/SG-bx-4_quality_filtering_stats.txt, stats=SG-bx-4/logs/SG-bx-4_quality_filtering_stats.txt, overwrite=true, qout=33, trd=t, hdist=1, k=27, ktrim=r, mink=8, trimq=10, qtrim=rl, threads=8, minlength=51, maxns=-1, minbasefrequency=0.05, ecco=t, prealloc=t, -Xmx51G]

Set INTERLEAVED to false                       
Set threads to 8                               
Initial size set to 506877058                  
maskMiddle was disabled because useShortKmers=true                                            
Exception in thread "main" java.lang.AssertionError: Duplicate file SG-bx-4/logs/SG-bx-4_quality_filtering_stats.txt was specified for multiple output streams.                             
        at shared.Tools.testOutputFiles(Tools.java:857)                                       
        at jgi.BBDukF.<init>(BBDukF.java:784)  
        at jgi.BBDukF.main(BBDukF.java:66)     
```

Thus, the file log output is specified twice in the shell command, once in `outs` and once in `stats`.

```
bbduk.sh in1=SG-WT-1/sequence_quality_control/SG-WT-1_deduplicated_R1.fastq.gz in2=SG-WT-1/sequence_quality_control/SG-WT-1_deduplicated_R2.fastq.gz               \
  ref=/data/projects/p532_BX-rhizosphere-metagenomics/metagenome-atlas/atlas/databases/adapters.fa    \
   interleaved=f                 \
  out=SG-WT-1/sequence_quality_control/SG-WT-1_filtered_R1.fastq.gz \
  out2=SG-WT-1/sequence_quality_control/SG-WT-1_filtered_R2.fastq.gz \
  outs=SG-WT-1/logs/SG-WT-1_quality_filtering_stats.txt                 \
  stats=SG-WT-1/logs/SG-WT-1_quality_filtering_stats.txt \
                overwrite=true                 qout=33                 trd=t                 hdist=1                 k=27                 ktrim=r                 mink=8                 trimq=10                 qtrim=rl                 threads=8                 minlength=51                 maxns=-1                 minbasefrequency=0.05                 ecco=t                 prealloc=t                 -Xmx51G 2> SG-WT-1/logs/QC/quality_filter.log
```

Did you come across this issue before? If yes, do you have a fix for this?

Thank you very much and let me know if you need any other information.

*Version*: atlas, version 2.3.0

**Comment by SilasK** [comment]
Sorry, I forgot this issue. I find it very strange that the outs points to the stats file instead to the singleton fastq file. 

I suggest to use `git pull` to update the atlas development mode. You should end up with atlas v.2.6a2 

If the error persists, please show me also the error message produced by the Snakemake output. stdout. 

v.2.6a2 should also be faster in installing packages.

**Comment by SilasK** [comment]
Sorry, I forgot this issue.

**Comment by makrez** [comment]
Hi Silas,

The download was indeed faster after updating to the newest version. However, the error persists.

Here is the stdout from Snakemake:

```
Error in rule apply_quality_filter:            
    jobid: 5                                   
    output: SG-bx-1/sequence_quality_control/SG-bx-1_filtered_R1.fastq.gz, SG-bx-1/sequence_quality_control/SG-bx-1_filtered_R2.fastq.gz, SG-bx-1/logs/SG-bx-1_quality_filtering_stats.txt  
    log: SG-bx-1/logs/QC/quality_filter.log (check log file(s) for error message)             
    conda-env: /data/projects/p532_BX-rhizosphere-metagenomics/metagenome-atlas_2/atlas/databases/conda_envs/ba1369d51e8ea211f4a9cee400f105f8                                               
    shell:                                     
                                               
            bbduk.sh in1=SG-bx-1/sequence_quality_control/SG-bx-1_deduplicated_R1.fastq.gz in2=SG-bx-1/sequence_quality_control/SG-bx-1_deduplicated_R2.fastq.gz                 ref=/data/projects/p532_BX-rhizosphere-metagenomics/metagenome-atlas_2/atlas/databases/adapters.fa                 interleaved=f                 out=SG-bx-1/sequence_quality_control/SG-bx-1_filtered_R1.fastq.gz out2=SG-bx-1/sequence_quality_control/SG-bx-1_filtered_R2.fastq.gz outs=SG-bx-1/logs/SG-bx-1_quality_filtering_stats.txt                 stats=SG-bx-1/logs/SG-bx-1_quality_filtering_stats.txt                 overwrite=true                 qout=33                 trd=t                 hdist=1                 k=27                 ktrim=r                 mink=8                 trimq=10                 qtrim=rl                 threads=12                 minlength=51                 maxns=-1                 minbasefrequency=0.05                 ecco=t                 prealloc=t                 -Xmx85G 2> SG-bx-1/logs/QC/quality_filter.log
                                               
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)                                                                                    
    cluster_jobid: 6842260                     

Error executing rule apply_quality_filter on cluster (jobid: 5, external: 6842260, jobscript: /data/projects/p532_BX-rhizosphere-metagenomics/metagenome-atlas_2/atlas/.snakemake/tmp.ddyjyzrp/snakejob.apply_quality_filter.5.sh). For error details see the cluster log and the log files of the involved rule(s).
```

**Comment by SilasK** [comment]
It seems the error is in my code. Or at least the code is not very robust. 

> SG-bx-1/sequence_quality_control/SG-bx-1_filtered_R1.fastq.gz, SG-bx-1/sequence_quality_control/SG-bx-1_filtered_R2.fastq.gz, SG-bx-1/logs/SG-bx-1_quality_filtering_stats.txt  

The third output file should be the singleton reads. I don't understand why the aren't.
Could you tell me what the headerline in your sample.tsv is. 

Did you use interleaved files as stating reads?

**Comment by makrez** [comment]
[samples.txt](https://github.com/metagenome-atlas/atlas/files/6727261/samples.txt)

I attach it here. I renamed it from `tsv` to `txt` since the former is not allowed for uploading here.

**Comment by SilasK** [comment]
Ah, there should be a empty column named `Reads_QC_se` in addition to the QC ones. 
You can also remove all columns as they are yet empty. I think.

We then will have three fastq file for each sample `R1,R2,se` the se are the singletons whose mate has too low quality. 
In this way the rule `apply_quality_filter` don't get confused. 

I don't know why there is a missing column but I agree that the programming is not very robust. 

O may sugest to simplify your sample names, as you are still quite at the beginign.

**Comment by SilasK** [comment]
I hope it's solved otherwise don't hesitate to comment.
