### ISSUE TITLE
AttributeError: 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by fconstancias** [metagenome-atlas/atlas#408]
Dear @SilasK,

Thanks for developing this amazing tool.

I have just freshly installed the latest atlas version

```console
(atlas) $ atlas --version
atlas, version 2.6a2
(atlas) $ atlas init --db-dir /db/atlas/ .
[2021-07-01 04:09 INFO] Configuration file written to /test_reads/config.yaml
You may want to edit it using any text editor.
[2021-07-01 04:09 INFO] Found 2 samples under .
```

And I got the following error when running the full pipeline locally (on a workstation) using the test data.

```console
(atlas) $ atlas run all --resources mem=245 --jobs 8
```

```console
[2021-07-01 04:13 INFO] Executing: snakemake --snakefile /home/constancias/miniconda3/envs/atlas/lib/python3.6/site-packages/atlas/Snakefile --directory /datadrive05/Flo/tools/test_reads --jobs 8 --rerun-incomplete --configfile '/datadrive05/Flo/tools/test_reads/config.yaml' --nolock   --use-conda --conda-prefix /datadrive05/Flo/db/atlas/conda_envs   --scheduler greedy  all  --resources mem=245 
Traceback (most recent call last):
  File "/home/constancias/miniconda3/envs/atlas/bin/snakemake", line 10, in <module>
    sys.exit(main())
  File "/home/constancias/miniconda3/envs/atlas/lib/python3.6/site-packages/snakemake/__init__.py", line 2400, in main
    resources = parse_resources(args.resources)
  File "/home/constancias/miniconda3/envs/atlas/lib/python3.6/site-packages/snakemake/resources.py", line 85, in parse_resources
    for res, val in resources_args.items():
AttributeError: 'list' object has no attribute 'items'
[2021-07-01 04:13 CRITICAL] Command 'snakemake --snakefile /home/constancias/miniconda3/envs/atlas/lib/python3.6/site-packages/atlas/Snakefile --directory /datadrive05/Flo/tools/test_reads --jobs 8 --rerun-incomplete --configfile '/datadrive05/Flo/tools/test_reads/config.yaml' --nolock   --use-conda --conda-prefix /datadrive05/Flo/db/atlas/conda_envs   --scheduler greedy  all  --resources mem=245 ' returned non-zero exit status 1.
```

Any idea what could be the issue here?

Thanks!

**Comment by SilasK** [comment]
Sorry for the inconvinience. It seems there is an error inside snakemake due to the --resource argument.

Could you raise the issue on the [snakemake repo](https://github.com/snakemake/snakemake/issues) while including a link to this issue. https://github.com/metagenome-atlas/atlas/issues/408

If you freshly installed atlas then you should have snakemake v6.3. Maybe try to update it to the most recent version of snakemake first. 

`mamba update snakemake`

**Comment by SilasK** [comment]
I hope it's solved otherwise don't hesitate to comment.
