### ISSUE TITLE
Permission denied in dereplication step

### ISSUE THREAD

**Issue by arsuke** [metagenome-atlas/atlas#412]
Hello
I am getting the following error in the deleplication step of Atlas.

```
***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************
    
Will filter the genome list
Calculating genome info of genomes
100.00% of genomes passed length filtering
71.43% of genomes passed checkM filtering
***************************************************
    ..:: dRep dereplicate Step 2. Cluster ::..
***************************************************
    
Clustering Step 1. Parse Arguments
Clustering Step 2. Perform MASH (primary) clustering
2a. Run pair-wise MASH clustering
2b. Cluster pair-wise MASH clustering
15 primary clusters made
Step 3. Perform secondary clustering
3. Nevermind! Skipping secondary clustering
Step 4. Return output
***************************************************
    ..:: dRep dereplicate Step 3. Choose ::..
***************************************************
    
Loading work directory
Traceback (most recent call last):
  File "/home/USER_NAME/metagenome_assebly/sing_atlas_Jan_150m/conda_envs/ea7616fb/bin/dRep", line 33, in <module>
    controller.parseArguments(args)
  File "/home/USER_NAME/metagenome_assebly/sing_atlas_Jan_150m/conda_envs/ea7616fb/lib/python3.6/site-packages/drep/controller.py", line 144, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/home/USER_NAME/metagenome_assebly/sing_atlas_Jan_150m/conda_envs/ea7616fb/lib/python3.6/site-packages/drep/controller.py", line 86, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/home/USER_NAME/metagenome_assebly/sing_atlas_Jan_150m/conda_envs/ea7616fb/lib/python3.6/site-packages/drep/d_workflows.py", line 44, in dereplicate_wrapper
    drep.d_choose.d_choose_wrapper(wd, **kwargs)
  File "/home/USER_NAME/metagenome_assebly/sing_atlas_Jan_150m/conda_envs/ea7616fb/lib/python3.6/site-packages/drep/d_choose.py", line 84, in d_choose_wrapper
    wd.store_special('dereplicated_genomes', derep_genomes)
  File "/home/USER_NAME/metagenome_assebly/sing_atlas_Jan_150m/conda_envs/ea7616fb/lib/python3.6/site-packages/drep/WorkDirectory.py", line 335, in store_special
    shutil.copy2(loc, "{0}{1}".format(output_folder,genome))
  File "/home/USER_NAME/metagenome_assebly/sing_atlas_Jan_150m/conda_envs/ea7616fb/lib/python3.6/shutil.py", line 264, in copy2
    copystat(src, dst, follow_symlinks=follow_symlinks)
  File "/home/USER_NAME/metagenome_assebly/sing_atlas_Jan_150m/conda_envs/ea7616fb/lib/python3.6/shutil.py", line 229, in copystat
    _copyxattr(src, dst, follow_symlinks=follow)
  File "/home/USER_NAME/metagenome_assebly/sing_atlas_Jan_150m/conda_envs/ea7616fb/lib/python3.6/shutil.py", line 165, in _copyxattr
    os.setxattr(dst, name, value, follow_symlinks=follow_symlinks)
PermissionError: [Errno 13] Permission denied: '/home/USER_NAME/metagenome_assebly/sing_atlas_Jan_150m/.snakemake/shadow/tmpi7eigxx5/genomes/pre_dereplication/dereplicated_genomes/21Jan-shizu-150m-shotgun-S25-merged-001_maxbin_34.fasta'


```

The problem is related to Permission, so it might be caused by the PC cluster settings.
Can you please tell me how to solve this problem?

Thank you.

[logger.log](https://github.com/metagenome-atlas/atlas/files/6827325/logger.log)

**Comment by SilasK** [comment]
You can use `--shadow-prefix DIR` to let atlas creat the intermediary files somewhere else. But I'm not sure it this solves the problem


It's seems you don't have the latest version. 
I update Drep in the latest version. I suggest you to run `atlas run binning` then update `mamba update metagenome-atlas` and run atlas again.
