### ISSUE TITLE
CheckM: Permission denied?

### ISSUE THREAD

**Issue by animesh** [metagenome-atlas/atlas#416]
I am facing this error in re-running

```
[2021-08-03 10:03:37] INFO: CheckM v1.1.3
[2021-08-03 10:03:37] INFO: checkm data setRoot /cluster/projects/nn9036k/reads/checkm
[2021-08-03 10:03:37] INFO: [CheckM - data] Check for database updates. [setRoot]

Unexpected error: <class 'NameError'>
Traceback (most recent call last):
  File "/cluster/software/CheckM/1.1.3-intel-2020a-Python-3.8.2/lib/python3.8/site-packages/checkm/checkmData.py", line 87, in checkPermissions
    open(self.configFile, 'a')
PermissionError: [Errno 13] Permission denied: '/cluster/software/CheckM/1.1.3-intel-2020a-Python-3.8.2/lib/python3.8/site-packages/checkm/DATA_CONFIG'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cluster/software/CheckM/1.1.3-intel-2020a-Python-3.8.2/bin/checkm", line 611, in <module>
    checkmParser.parseOptions(args)
  File "/cluster/software/CheckM/1.1.3-intel-2020a-Python-3.8.2/lib/python3.8/site-packages/checkm/main.py", line 834, in parseOptions
    self.updateCheckM_DB(options)
  File "/cluster/software/CheckM/1.1.3-intel-2020a-Python-3.8.2/lib/python3.8/site-packages/checkm/main.py", line 78, in updateCheckM_DB
    DBM = DBManager(set_path=action[1])
  File "/cluster/software/CheckM/1.1.3-intel-2020a-Python-3.8.2/lib/python3.8/site-packages/checkm/checkmData.py", line 107, in __init__
    self.setRoot(set_path)
  File "/cluster/software/CheckM/1.1.3-intel-2020a-Python-3.8.2/lib/python3.8/site-packages/checkm/checkmData.py", line 142, in setRoot
    if not self.config.checkPermissions():
  File "/cluster/software/CheckM/1.1.3-intel-2020a-Python-3.8.2/lib/python3.8/site-packages/checkm/checkmData.py", line 88, in checkPermissions
    except (IOError, e):
NameError: name 'e' is not defined
```

Any ideas on how to go beyond this?

**Comment by SilasK** [comment]
We encountered this issue before. We solved it by forcing to use python3.6 in combination with check.
https://github.com/metagenome-atlas/atlas/issues/369#issuecomment-780514918

Either you update atlas to a version > 2.6a2  or, maybe easier, you make the following change only on your computer. 
bbdabd6

Don't hesitate to come back.
