### ISSUE TITLE
Error in rule apply_quality_filter

### ISSUE THREAD

**Issue by mewu3** [metagenome-atlas/atlas#432]
Hello, 

Here it's the stdout message. 

```
Error in rule apply_quality_filter:
    jobid: 5
    output: sample2/sequence_quality_control/sample2_filtered_R1.fastq.gz, sample2/sequence_quality_control/sample2_filtered_R2.fastq.gz, sample2/sequence_quality_control/sample2_filtered_se.fastq.gz, sample2/logs/sample2_quality_filtering_stats.txt
    log: sample2/logs/QC/quality_filter.log (check log file(s) for error message)
    conda-env: /home/meijun/Téléchargements/databases/conda_envs/8d0d2580af940e1c05fa109448ac8e92
    shell:
        
            bbduk.sh in1=sample2/sequence_quality_control/sample2_deduplicated_R1.fastq.gz in2=sample2/sequence_quality_control/sample2_deduplicated_R2.fastq.gz                 ref=/home/meijun/Téléchargements/databases/adapters.fa                 interleaved=f                 out=sample2/sequence_quality_control/sample2_filtered_R1.fastq.gz out2=sample2/sequence_quality_control/sample2_filtered_R2.fastq.gz outs=sample2/sequence_quality_control/sample2_filtered_se.fastq.gz                 stats=sample2/logs/sample2_quality_filtering_stats.txt                 overwrite=true                 qout=33                 trd=t                 hdist=1                 k=27                 ktrim=r                 mink=8                 trimq=10                 qtrim=rl                 threads=4                 minlength=51                 maxns=-1                 minbasefrequency=0.05                 ecco=t                 prealloc=t                 -Xmx51G 2> sample2/logs/QC/quality_filter.log
            
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Note the path to the log file for debugging.
Documentation is available at: https://metagenome-atlas.readthedocs.io
Issues can be raised at: https://github.com/metagenome-atlas/atlas/issues
```
log file message:
```
java -Djava.library.path=/home/meijun/Téléchargements/databases/conda_envs/8d0d2580af940e1c05fa109448ac8e92/opt/bbmap-37.99/jni/ -ea -Xmx51G -Xms51G -cp /home/meijun/Téléchargements/databases/conda_envs/8d0d2580af940e1c05fa109448ac8e92/opt/bbmap-37.99/current/ jgi.BBDukF in1=sample2/sequence_quality_control/sample2_deduplicated_R1.fastq.gz in2=sample2/sequence_quality_control/sample2_deduplicated_R2.fastq.gz ref=/home/meijun/Téléchargements/databases/adapters.fa interleaved=f out=sample2/sequence_quality_control/sample2_filtered_R1.fastq.gz out2=sample2/sequence_quality_control/sample2_filtered_R2.fastq.gz outs=sample2/sequence_quality_control/sample2_filtered_se.fastq.gz stats=sample2/logs/sample2_quality_filtering_stats.txt overwrite=true qout=33 trd=t hdist=1 k=27 ktrim=r mink=8 trimq=10 qtrim=rl threads=8 minlength=51 maxns=-1 minbasefrequency=0.05 ecco=t prealloc=t -Xmx51G
Executing jgi.BBDukF [in1=sample2/sequence_quality_control/sample2_deduplicated_R1.fastq.gz, in2=sample2/sequence_quality_control/sample2_deduplicated_R2.fastq.gz, ref=/home/meijun/Téléchargements/databases/adapters.fa, interleaved=f, out=sample2/sequence_quality_control/sample2_filtered_R1.fastq.gz, out2=sample2/sequence_quality_control/sample2_filtered_R2.fastq.gz, outs=sample2/sequence_quality_control/sample2_filtered_se.fastq.gz, stats=sample2/logs/sample2_quality_filtering_stats.txt, overwrite=true, qout=33, trd=t, hdist=1, k=27, ktrim=r, mink=8, trimq=10, qtrim=rl, threads=8, minlength=51, maxns=-1, minbasefrequency=0.05, ecco=t, prealloc=t, -Xmx51G]
Version 37.99 [in1=sample2/sequence_quality_control/sample2_deduplicated_R1.fastq.gz, in2=sample2/sequence_quality_control/sample2_deduplicated_R2.fastq.gz, ref=/home/meijun/Téléchargements/databases/adapters.fa, interleaved=f, out=sample2/sequence_quality_control/sample2_filtered_R1.fastq.gz, out2=sample2/sequence_quality_control/sample2_filtered_R2.fastq.gz, outs=sample2/sequence_quality_control/sample2_filtered_se.fastq.gz, stats=sample2/logs/sample2_quality_filtering_stats.txt, overwrite=true, qout=33, trd=t, hdist=1, k=27, ktrim=r, mink=8, trimq=10, qtrim=rl, threads=8, minlength=51, maxns=-1, minbasefrequency=0.05, ecco=t, prealloc=t, -Xmx51G]

Set INTERLEAVED to false
Set threads to 8
Initial size set to 506877058
maskMiddle was disabled because useShortKmers=true
Warning!  Cannot find primes.txt.gz /home/meijun/T%c3%a9l%c3%a9chargements/databases/conda_envs/8d0d2580af940e1c05fa109448ac8e92/opt/bbmap-37.99/current/primes.txt.gz
java.lang.Exception
	at dna.Data.findPath(Data.java:1243)
	at shared.Primes.fetchPrimes(Primes.java:163)
	at shared.Primes.<clinit>(Primes.java:173)
	at kmer.HashArray.<clinit>(HashArray.java:493)
	at kmer.AbstractKmerTable$AllocThread.run(AbstractKmerTable.java:422)
Exception in thread "Thread-0" Exception in thread "Thread-1" java.lang.ExceptionInInitializerError
	at kmer.HashArray.<clinit>(HashArray.java:493)
	at kmer.AbstractKmerTable$AllocThread.run(AbstractKmerTable.java:422)
Caused by: java.lang.NullPointerException
	at fileIO.ByteFile.<init>(ByteFile.java:33)
	at fileIO.ByteFile1.<init>(ByteFile1.java:98)
	at fileIO.ByteFile1.<init>(ByteFile1.java:94)
	at shared.Primes.fetchPrimes(Primes.java:165)
	at shared.Primes.<clinit>(Primes.java:173)
	... 2 more
java.lang.NoClassDefFoundError: Could not initialize class kmer.HashArray1D
	at kmer.AbstractKmerTable$AllocThread.run(AbstractKmerTable.java:422)
0.014 seconds.
Exception in thread "main" java.lang.RuntimeException: KmerTable allocation failed, probably due to lack of RAM: 0, 7
	at kmer.AbstractKmerTable.preallocate(AbstractKmerTable.java:389)
	at jgi.BBDukF.<init>(BBDukF.java:836)
	at jgi.BBDukF.main(BBDukF.java:66)
```

mewu3

**Comment by SilasK** [comment]
> KmerTable allocation failed, probably due to lack of RAM: 0, 7
Could this be the problem?


Check if you have enough memory:
the value of mem in the config file in GB.

Also see if you run atlas correctly. 
 https://metagenome-atlas.readthedocs.io/en/latest/usage/getting_started.html#execue-atlas

**Comment by mewu3** [comment]
I do believe i fallow the instruction document step by step, and there are 131 GB memory. 
```
grep MemTotal /proc/meminfo
MemTotal:       131850436 kB
```

**Comment by SilasK** [comment]
Try to increase the mem value in the config. maybe you just need to give more memory to the tool. 
By the way new version of atlas is on conda, please update. You can continue directly with the new version.
