### ISSUE TITLE
Error in opening Jupyter Notebook for Tutorial

### ISSUE THREAD

**Issue by bryshalm** [metagenome-atlas/atlas#472]
- [ ] I checked and didn't found a related issue regarding Jupyter Notebook
- [ ] ** I got an error in the following rule(s):** `  TypeError: __init__() got an unexpected keyword argument 'capture_output'  `

Traceback (most recent call last):
File "/srv/conda/envs/notebook/lib/python3.6/site-packages/nbgitpuller/handlers.py", line 76, in get
    gp = GitPuller(repo, repo_dir, branch=branch, depth=depth, parent=self.settings['nbapp'])
File "/srv/conda/envs/notebook/lib/python3.6/site-packages/nbgitpuller/pull.py", line 77, in __init__
    elif not self.branch_exists(self.branch_name):
File "/srv/conda/envs/notebook/lib/python3.6/site-packages/nbgitpuller/pull.py", line 94, in branch_exists
    check=True
File "/srv/conda/envs/notebook/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'

Was able to open in RStudio

**Comment by SilasK** [comment]
I will work on that this week. The Rmd should be up to data.

**Comment by SilasK** [comment]
I updated the python tutorial have a look !
