### ISSUE TITLE
DRAM_annotate fails at pfam step

### ISSUE THREAD

**Issue by slambrechts** [metagenome-atlas/atlas#481]
When rerunning `atlas run genomes` to get the DRAM output per MAG, the rule `DRAM_annotate` seems to fail at the pfam step (for each MAG) according to the `log/dram/run_dram/MAGxxx.log` files:

```
/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/55755f7f85ad0d62630d9439fcf17162/lib/python3.9/site-packages/mag_annotator/annotate_bins.py:120: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  hits[forward_hit] = [row.tId, rbh, row.seqIdentity, row.bitScore, row.eVal]
/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/55755f7f85ad0d62630d9439fcf17162/lib/python3.9/site-packages/mag_annotator/database_handler.py:42: UserWarning: No descriptions were found for your id's. Does this PF02773.18 look like an id from pfam_description
  warn("No descriptions were found for your id's. Does this %s look like an id from %s" % (list(ids)[0],
1 fastas found
2021-11-29 17:14:30.225208: Annotation started
0:00:00.083813: Retrieved database locations and descriptions
0:00:00.083835: Annotating MAG015
0:00:47.475971: Turning genes from prodigal to mmseqs2 db
0:00:48.481523: Getting hits from kofam
0:25:22.741176: Getting forward best hits from peptidase
0:25:43.075736: Getting reverse best hits from peptidase
0:25:45.598773: Getting descriptions of hits from peptidase
0:25:45.653240: Getting hits from pfam
Traceback (most recent call last):
  File "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/55755f7f85ad0d62630d9439fcf17162/bin/DRAM.py", line 168, in <module>
    args.func(**args_dict)
  File "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/55755f7f85ad0d62630d9439fcf17162/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 967, in annotate_bins_cmd
    annotate_bins(fasta_locs, output_dir, min_contig_size, prodigal_mode, trans_table, bit_score_threshold,
  File "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/55755f7f85ad0d62630d9439fcf17162/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 1006, in annotate_bins
    all_annotations = annotate_fastas(fasta_locs, output_dir, db_locs, db_handler, min_contig_size, prodigal_mode,
  File "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/55755f7f85ad0d62630d9439fcf17162/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 944, in annotate_fastas
    annotations_list.append(annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_locs, db_handler, min_contig_size,
  File "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/55755f7f85ad0d62630d9439fcf17162/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 845, in annotate_fasta
    annotations = annotate_orfs(gene_faa, db_locs, tmp_dir, start_time, db_handler, custom_db_locs, bit_score_threshold,
  File "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/55755f7f85ad0d62630d9439fcf17162/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 786, in annotate_orfs
    annotation_list.append(run_mmseqs_profile_search(query_db, db_locs['pfam'], tmp_dir, output_prefix='pfam',
  File "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/55755f7f85ad0d62630d9439fcf17162/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 204, in run_mmseqs_profile_search
    pfam_dict[gene] = '; '.join(['%s [%s]' % (pfam_descriptions[ascession], ascession)
  File "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/55755f7f85ad0d62630d9439fcf17162/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 204, in <listcomp>
    pfam_dict[gene] = '; '.join(['%s [%s]' % (pfam_descriptions[ascession], ascession)
KeyError: 'PF09951.11'

```

But in the `log/dram/run_dram/subset_x.log` files it says:

```
/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/55755f7f85ad0d62630d9439fcf17162/lib/python3.9/site-packages/mag_annotator/annotate_bins.py:989: UserWarning: When running prodigal in single mode your bins must have long contigs (average length >3 Kbp), be long enough (total length > 500 Kbp) and have very low contamination in order for prodigal training to work well.
  warnings.warn('When running prodigal in single mode your bins must have long contigs (average length >3 Kbp), '
1 fastas found
2021-10-01 16:35:46.073999: Annotation started
Traceback (most recent call last):
  File "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/55755f7f85ad0d62630d9439fcf17162/bin/DRAM.py", line 168, in <module>
    args.func(**args_dict)
  File "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/55755f7f85ad0d62630d9439fcf17162/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 967, in annotate_bins_cmd
    annotate_bins(fasta_locs, output_dir, min_contig_size, prodigal_mode, trans_table, bit_score_threshold,
  File "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/55755f7f85ad0d62630d9439fcf17162/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 1001, in annotate_bins
    db_handler = DatabaseHandler(db_locs['description_db'])
  File "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/55755f7f85ad0d62630d9439fcf17162/lib/python3.9/site-packages/mag_annotator/database_handler.py", line 17, in __init__
    raise ValueError('Database does not exist at path %s' % database_loc)
ValueError: Database does not exist at path None

```

So from the subset log it would seem the database is not found, but that doesn't seem to be the case from the MAG logs.

Or is it and do I need to touch a specific rule so atlas knows the DRAM database download and preparation is finished (because I had to do the download and preparation manually)?

DAG of jobs was:
```

Job stats:
job                   count    min threads    max threads
------------------  -------  -------------  -------------
DRAM_annotate           289              8              8
DRAM_destill              1              1              1
concat_annotations        1              1              1
genomes                   1              1              1
get_all_modules           1              1              1
total                   293              1              8

This was a dry-run (flag -n). The order of jobs does not reflect the order of execution.
(atlas-28) [vsc42339@node3586 CLEAN_READS]$
```

**Comment by SilasK** [comment]
Ok, I assume the database for Pfam is not downloaded and so dram throws an error at the first pfam it wants to look up.


You downloaded the dram databases independently. Probably it's just that the dram in atlas doesn't know the exact path. 

1. remove the file `"{ATLAS_DBDIR}/dram_config_imported"` to tell atlas to reimport it.
2. use the dram version you used to download the databases. Or simply the dram in atlas via `conda activate  /kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/conda_envs/55755f7f85ad0d62630d9439fcf17162`
3. Run `DRAM-setup.py export_config ` To get the dram config file, with probably a missing Pfam database
4. Fix the pfam path (and potentially others) (Uniref is not downloaded)
5. Save the DRAM file to `{ATLASDBDIR}/DRAM.config` or specify the path in in the atlas config file with the keyword `dram_config_file``

6. Run atlas (dryrun). Atlas should import the config file and then run the dram rules.

**Comment by slambrechts** [comment]
Ok thanks. I did all that, but it doesn't seem to work.

The Pfam database was downloaded while running `DRAM-setup.py`, together with the other databases. The following Pfam files are in `/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/Dram/database_files`:


```
Pfam-A.full.gz
Pfam-A.hmm.dat.gz
pfam.mmspro
pfam.mmspro.dbtype
pfam.mmspro_h
pfam.mmspro_h.dbtype
pfam.mmspro_h.index
pfam.mmspro.idx
pfam.mmspro.idx.dbtype
pfam.mmspro.idx.index
pfam.mmspro.index

```

and `/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/DRAM.config` contains both a correct "pfam" and "pfam_hmm_dat" location:
```
"pfam": "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/Dram/database_files/pfam.mmspro", "pfam_hmm_dat": "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/Dram/database_files/Pfam-A.hmm.dat.gz"
```

Full `DRAM.confilg` file:

```
{"kegg": null, "kofam": "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/Dram/database_files/kofam_profiles.hmm", "kofam_ko_list": "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/Dram/database_files/kofam_ko_list.tsv", "uniref": null, "pfam": "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/Dram/database_files/pfam.mmspro", "pfam_hmm_dat": "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/Dram/database_files/Pfam-A.hmm.dat.gz", "dbcan": "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/Dram/database_files/dbCAN-HMMdb-V9.txt", "dbcan_fam_activities": "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/Dram/database_files/CAZyDB.07302020.fam-activities.txt", "viral": "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/Dram/database_files/refseq_viral.20211124.mmsdb", "peptidase": "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/Dram/database_files/peptidases.20211124.mmsdb", "vogdb": "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/Dram/database_files/vog_latest_hmms.txt", "vog_annotations": "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/Dram/database_files/vog_annotations_latest.tsv.gz", "genome_summary_form": "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/Dram/database_files/genome_summary_form.20211124.tsv", "module_step_form": "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/Dram/database_files/module_step_form.20211124.tsv", "etc_module_database": "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/Dram/database_files/etc_mdoule_database.20211124.tsv", "function_heatmap_form": "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/Dram/database_files/function_heatmap_form.20211124.tsv", "amg_database": "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/Dram/database_files/amg_database.20211124.tsv", "description_db": "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/MICROBIAN/atlas/DB/Dram/database_files/description_db.sqlite"}
```

I wonder why it works for kofam and the peptidases, but not for pfam

It also happens when I run `DRAM.py annotate -i 'genomes/genomes/*.fasta' -o DRAM --threads 48` with the DRAM version with which I downloaded the databases

I will open an issue on the DRAM github
