### ISSUE TITLE
Error in rule build_bin_report

### ISSUE THREAD

**Issue by cmorganl** [metagenome-atlas/atlas#508]
- [x] I checked and didn't found a related issue,e.g. while typing the title
- [x] ** I got an error in the following rule(s):** `build_bin_report `

- [x] I checked the log files indicated indicated in the error message (and the cluster logs if submitted to a cluster)

Here is the relevant log output (from `logs/binning/report_DASTool.log`):

```
2022-04-14 14:12:42 Uncaught exception: Traceback (most recent call last):
  File "/datadrive/ATLAS/Output/.snakemake/scripts/tmph3p7hxsj.bin_report.py", line 108, in <module>
    div = make_plots(bin_table=snakemake.input.bin_table)
  File "/datadrive/ATLAS/Output/.snakemake/scripts/tmph3p7hxsj.bin_report.py", line 66, in make_plots
    fig = px.scatter(
  File "/datadrive/AtlasDB/conda_envs/01fab9ef545bf1ad478b7add8cde5734/lib/python3.9/site-packages/plotly/express/_chart_types.py", line 66, in scatter
    return make_figure(args=locals(), constructor=go.Scatter)
  File "/datadrive/AtlasDB/conda_envs/01fab9ef545bf1ad478b7add8cde5734/lib/python3.9/site-packages/plotly/express/_core.py", line 1933, in make_figure
    args = build_dataframe(args, constructor)
  File "/datadrive/AtlasDB/conda_envs/01fab9ef545bf1ad478b7add8cde5734/lib/python3.9/site-packages/plotly/express/_core.py", line 1405, in build_dataframe
    df_output, wide_id_vars = process_args_into_dataframe(
  File "/datadrive/AtlasDB/conda_envs/01fab9ef545bf1ad478b7add8cde5734/lib/python3.9/site-packages/plotly/express/_core.py", line 1207, in process_args_into_dataframe
    raise ValueError(err_msg)
ValueError: Value of 'hover_data_0' is not the name of a column in 'data_frame'. Expected one of ['Bin Id', 'Completeness', 'Contamination', 'Strain heterogeneity', '# unique markers (of 43)', '# multi-copy', 'Insertion branch UID', 'Taxonomy (contained)', 'Taxonomy (sister lineage)', 'GC', 'Genome size (Mbp)', 'Gene count', 'Coding density', 'Sample', 'Domain', 'phylum', 'class', 'order', 'family', 'Quality Score'] but received: genus
```

** Atlas version**
2.9.0

**Additional context**
Running ATLAS on an Azure VM with Ubuntu 20.04. ATLAS was installed using conda as per install instructions.

**Comment by SilasK** [comment]
Ok, It seems that your bins are somewhat undefined, but I should find a better solution.

This rule should produce a report, but all the important data is there and should be the input to this rule. Check the quality metrics to see how many bins you have. 

Then You can run atlas with `--omit-from build_bin_report` to let it run without this report. You will get a proper taxonomy later.
