### ISSUE TITLE
Error in rule run_checkm_lineage_wf

### ISSUE THREAD

**Issue by HamzaMbareche** [metagenome-atlas/atlas#525]
Hi Silas,

I'm getting an error while running _atlas run genomes_  at the _run_checkm_lineage_wf_ step.

Unexpected error: <class 'FileNotFoundError'>
Traceback (most recent call last):
  File "/media/hmbareche/data2/MAGs_Discovery/databases/conda_envs/10823abaad34c874ce80d23b3c9ee80d/bin/checkm", line 856, in <module>
    checkmParser.parseOptions(args)
  File "/media/hmbareche/data2/MAGs_Discovery/databases/conda_envs/10823abaad34c874ce80d23b3c9ee80d/lib/python3.6/site-packages/checkm/main.py", line 982, in parseOptions
    self.lineageSet(options)
  File "/media/hmbareche/data2/MAGs_Discovery/databases/conda_envs/10823abaad34c874ce80d23b3c9ee80d/lib/python3.6/site-packages/checkm/main.py", line 265, in lineageSet
    resultsParser, options.unique, options.multi)
  File "/media/hmbareche/data2/MAGs_Discovery/databases/conda_envs/10823abaad34c874ce80d23b3c9ee80d/lib/python3.6/site-packages/checkm/treeParser.py", line 485, in getBinMarkerSets
    tree = dendropy.Tree.get_from_path(treeFile, schema='newick', rooting="force-rooted", preserve_underscores=True)
  File "/media/hmbareche/data2/MAGs_Discovery/databases/conda_envs/10823abaad34c874ce80d23b3c9ee80d/lib/python3.6/site-packages/dendropy/datamodel/basemodel.py", line 216, in get_from_path
    with open(src, "r", newline=None) as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'S2119C1/binning/DASTool/checkm/storage/tree/concatenated.tre'

The code seems to be looking for a file that wasn't created: S2119C1/binning/DASTool/checkm/storage/tree/concatenated.tre

Is it an error in the script or am i overlooking something?

Alternatively, is there a way to continue the pipeline without the tree? The pipeline is 87% complete at this stage. 

I attached the complete checkm log file for your reference.
[checkm.log](https://github.com/metagenome-atlas/atlas/files/8799572/checkm.log)

Thanks for your continuous help. 

Best,
Hamza

**Comment by HamzaMbareche** [comment]
Hi Silas,

After running:

`export LC_ALL=C`

I'm getting a new error at that same step:

```
Finished aligning 43 of 43 (100.00%) marker genes.
Uncaught exception: Failure("S2119C1/binning/DASTool/checkm/storage/tree/concatenated.pplacer.json has no placements!")
Fatal error: exception Failure("S2119C1/binning/DASTool/checkm/storage/tree/concatenated.pplacer.json has no placements!")
    Finished parsing hits for 1 of 46 (2.17%) bins.
```
The last error of the checkM log is still the same:

```
Unexpected error: <class 'FileNotFoundError'>
Traceback (most recent call last):
  File "/media/hmbareche/data2/MAGs_Discovery/databases/conda_envs/10823abaad34c874ce80d23b3c9ee80d/bin/checkm", line 856, in <module>
    checkmParser.parseOptions(args)
  File "/media/hmbareche/data2/MAGs_Discovery/databases/conda_envs/10823abaad34c874ce80d23b3c9ee80d/lib/python3.6/site-packages/checkm/main.py", line 982, in parseOptions
    self.lineageSet(options)
  File "/media/hmbareche/data2/MAGs_Discovery/databases/conda_envs/10823abaad34c874ce80d23b3c9ee80d/lib/python3.6/site-packages/checkm/main.py", line 265, in lineageSet
    resultsParser, options.unique, options.multi)
  File "/media/hmbareche/data2/MAGs_Discovery/databases/conda_envs/10823abaad34c874ce80d23b3c9ee80d/lib/python3.6/site-packages/checkm/treeParser.py", line 485, in getBinMarkerSets
    tree = dendropy.Tree.get_from_path(treeFile, schema='newick', rooting="force-rooted", preserve_underscores=True)
  File "/media/hmbareche/data2/MAGs_Discovery/databases/conda_envs/10823abaad34c874ce80d23b3c9ee80d/lib/python3.6/site-packages/dendropy/datamodel/basemodel.py", line 216, in get_from_path
    with open(src, "r", newline=None) as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'S2119C1/binning/DASTool/checkm/storage/tree/concatenated.tre'

```

I attached the log file if you want to check it out. 

[checkm.log](https://github.com/metagenome-atlas/atlas/files/8805714/checkm.log)

Thanks again for your help. 

Best,
Hamza

**Comment by SilasK** [comment]
Sorry for the delay. 
With --keep-going you get the independent part of Atlas done. 

Happen this error only in one sample, then you might remove it from the sample table. 

Can you check in the sample/Binning/Das Tool/ folder there should z a summary with a rough quality estimation.

**Comment by HamzaMbareche** [comment]
Hi Silas, 

Sorry for the confusion but I meant that even with the --keep-going option, atlas failed and stoped at the following step.

If we put aside the --keep-going option, do you have an idea what may be the issue with the run_checkm_lineage?

Your suggestion of` export LC_ALL=C` definitely changed something as it's a different error message now:

```
Finished aligning 43 of 43 (100.00%) marker genes.
Uncaught exception: Failure("S2119C1/binning/DASTool/checkm/storage/tree/concatenated.pplacer.json has no placements!")
Fatal error: exception Failure("S2119C1/binning/DASTool/checkm/storage/tree/concatenated.pplacer.json has no placements!")
    Finished parsing hits for 1 of 46 (2.17%) bins.
```
I attached the full checkm.log file. 
[checkm.log](https://github.com/metagenome-atlas/atlas/files/8836618/checkm.log)

I also checked the summary at the sample/binning/DAStool/ at the quality seems good. Here's the tsv file of one sample:
[S1008C1_DASTool_summary.txt](https://github.com/metagenome-atlas/atlas/files/8836619/S1008C1_DASTool_summary.txt)

Thanks, 
Hamza

**Comment by SilasK** [comment]
I asked the developers of checkM 

https://github.com/Ecogenomics/CheckM/issues/337#issuecomment-1146701400

 they told me that's probably related to little memory.

Do you run Atlas via the cluster?
Anyway, try to increase the memory argument in the config.yaml

**Comment by HamzaMbareche** [comment]
I just had access to a cluster where I am running Atlas. The checkM error is fixed so the memory hypothesis is probably true.
