### ISSUE TITLE
Error in rule run_checkm_lineage_wf. UPDATE

### ISSUE THREAD

**Issue by HamzaMbareche** [metagenome-atlas/atlas#526]
Hi Silas,

After running:

`export LC_ALL=C`

I'm getting a different error at that same step:

```
Finished aligning 43 of 43 (100.00%) marker genes.
Uncaught exception: Failure("S2119C1/binning/DASTool/checkm/storage/tree/concatenated.pplacer.json has no placements!")
Fatal error: exception Failure("S2119C1/binning/DASTool/checkm/storage/tree/concatenated.pplacer.json has no placements!")
    Finished parsing hits for 1 of 46 (2.17%) bins.
```
The last error of the checkM log is still the same:

```
Unexpected error: <class 'FileNotFoundError'>
Traceback (most recent call last):
  File "/media/hmbareche/data2/MAGs_Discovery/databases/conda_envs/10823abaad34c874ce80d23b3c9ee80d/bin/checkm", line 856, in <module>
    checkmParser.parseOptions(args)
  File "/media/hmbareche/data2/MAGs_Discovery/databases/conda_envs/10823abaad34c874ce80d23b3c9ee80d/lib/python3.6/site-packages/checkm/main.py", line 982, in parseOptions
    self.lineageSet(options)
  File "/media/hmbareche/data2/MAGs_Discovery/databases/conda_envs/10823abaad34c874ce80d23b3c9ee80d/lib/python3.6/site-packages/checkm/main.py", line 265, in lineageSet
    resultsParser, options.unique, options.multi)
  File "/media/hmbareche/data2/MAGs_Discovery/databases/conda_envs/10823abaad34c874ce80d23b3c9ee80d/lib/python3.6/site-packages/checkm/treeParser.py", line 485, in getBinMarkerSets
    tree = dendropy.Tree.get_from_path(treeFile, schema='newick', rooting="force-rooted", preserve_underscores=True)
  File "/media/hmbareche/data2/MAGs_Discovery/databases/conda_envs/10823abaad34c874ce80d23b3c9ee80d/lib/python3.6/site-packages/dendropy/datamodel/basemodel.py", line 216, in get_from_path
    with open(src, "r", newline=None) as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'S2119C1/binning/DASTool/checkm/storage/tree/concatenated.tre'

```

I attached the log file if you want to check it out. 

[checkm.log](https://github.com/metagenome-atlas/atlas/files/8805714/checkm.log)

I also tried to run atlas run genomes --keep-going, and got a weird result where just 2 out of 22 samples completed the next job before atlas failing completely. 

Thanks again for your help. 

Best,
Hamza

_Originally posted by @HamzaMbareche in https://github.com/metagenome-atlas/atlas/issues/525#issuecomment-1142164307_

**Comment by SilasK** [comment]
I assume this error is solved, but don't hesitate to reopen the issue.
