### ISSUE TITLE
Error in rule

### ISSUE THREAD

**Issue by Nachida08** [metagenome-atlas/atlas#531]
-  I checked and didn't found a related issue,e.g. while typing the title
-  ** I got an error in the following rule(s):** ` run_megahit  `

- I checked the log files indicated indicated in the error message (and the cluster logs if submitted to a cluster)

Here is the relevant log output:

```
Error executing rule run_megahit on cluster (jobid: 23, external: 731789, jobscript: /usr/home/biopatic-DATA/tadrent/SnakeMAGs/benchmark_SnakeMAGs_Atlas/Atlas/atlas_DRR097505/.snakemake/tmp.yut9mft3/snakejob.run_megahit.23.sh). For error details see the cluster log and the log files of the involved rule(s).
Job failed, going on with independent jobs.
Exiting because a job execution failed. Look above for error message
BUG: Out of jobs ready to be started, but not all files built yet. Please check https://github.com/snakemake/snakemake/issues/823 for more information.

```

** Atlas 2.9.1**

Hi Silas,

I was running atlas on cluster slurm with 500 GB ram and 16 threads for assembly. Everything worked fine from QC until Megahit assembly. Do you have any idea of the source of the problem or what to do to solve it?
The cluster log and the rule log are ampty. 

Thank you

**Comment by Nachida08** [comment]
Hi,
I rerun atlas and I had this error in logs/assembly/megahit.log
```
Traceback (most recent call last):
  File "/usr/home/biopatic-Softwares/tadrent/ATLAS.2.9.1/databases/conda_envs/fa45b02db30f986ac64cec5b05fe8c62/bin/megahit", line 1038, in <module>
    main()
  File "/usr/home/biopatic-Softwares/tadrent/ATLAS.2.9.1/databases/conda_envs/fa45b02db30f986ac64cec5b05fe8c62/bin/megahit", line 977, in main
    parse_option(argv[1:])
  File "/usr/home/biopatic-Softwares/tadrent/ATLAS.2.9.1/databases/conda_envs/fa45b02db30f986ac64cec5b05fe8c62/bin/megahit", line 351, in parse_option
    opt.min_contig_len = int(value)
ValueError: invalid literal for int() with base 10: '1i000'
```

**Comment by SilasK** [comment]
Do you find something in the cluster log file with the id `731789`. If you use my cluster wrapper it is in cluter_logs/

Anything else in the megahit log file.

Is there a reason why you use megahit and not spades?
