### ISSUE TITLE
Error in rule classify

### ISSUE THREAD

**Issue by skeffington** [metagenome-atlas/atlas#540]
So I got classify to run on a high memory node, giving it 600 Gb and 8 threads. Previously it failed due to only having 128 Gb memory, so I modified the configuration and restarted. However now I get a 'FileExistsError'. Is this because not all files created by the previous attempt were removed by the snakemake workflow when it failed? 

Any ideas of how to proceed would be very welcome!

Thanks, 
Alastair

See classify.txt log below:

```

[2022-07-28 11:40:23] INFO: GTDB-Tk v1.5.1
[2022-07-28 11:40:23] INFO: gtdbtk classify --genome_dir genomes/genomes --align_dir genomes/taxonomy/gtdb --out_dir genomes/taxonomy/gtdb --extension fasta --cpus 8
[2022-07-28 11:40:23] INFO: Using GTDB-Tk reference data version r202: /lustre/projects/Research_Project-T115468/atlas_databases/GTDB_V06
[2022-07-28 11:40:25] TASK: Placing 2 archaeal genomes into reference tree with pplacer using 8 CPUs (be patient).
[2022-07-28 11:40:25] INFO: pplacer version: v1.1.alpha19-0-g807f6f3

==> .
==> Step 1 of 9: Starting pplacer.
==> Running pplacer v1.1.alpha19-0-g807f6f3 analysis on genomes/taxonomy/gtdb/align/gtdbtk.ar122.user_msa.fasta....
==> Step 2 of 9: Pre-masking sequences.                                                                            
==> Step 3 of 9: Determining figs.     
==> Step 4 of 9: Allocating memory for internal nodes.
==> Step 4 of 9 Allocating memory for internal nodes (11.35 GB).
==> Step 5 of 9: Caching likelihood information on reference tree.
==> Step 5 of 9: Caching likelihood information on reference tree (0.96/11.71 GB, 8.20%).
==> Step 5 of 9: Caching likelihood information on reference tree (1.60/11.71 GB, 13.65%).
==> Step 5 of 9: Caching likelihood information on reference tree (2.24/11.71 GB, 19.13%).
==> Step 5 of 9: Caching likelihood information on reference tree (2.88/11.71 GB, 24.63%).
==> Step 5 of 9: Caching likelihood information on reference tree (3.53/11.71 GB, 30.11%).
==> Step 5 of 9: Caching likelihood information on reference tree (4.17/11.71 GB, 35.58%).
==> Step 5 of 9: Caching likelihood information on reference tree (4.81/11.71 GB, 41.09%).
==> Step 5 of 9: Caching likelihood information on reference tree (5.45/11.71 GB, 46.57%).
==> Step 5 of 9: Caching likelihood information on reference tree (6.10/11.71 GB, 52.07%).
==> Step 5 of 9: Caching likelihood information on reference tree (6.74/11.71 GB, 57.56%).
==> Step 5 of 9: Caching likelihood information on reference tree (7.38/11.71 GB, 63.03%).
==> Step 5 of 9: Caching likelihood information on reference tree (8.01/11.71 GB, 68.35%).
==> Step 5 of 9: Caching likelihood information on reference tree (8.57/11.71 GB, 73.17%).
==> Step 5 of 9: Caching likelihood information on reference tree (9.14/11.71 GB, 78.04%).
==> Step 5 of 9: Caching likelihood information on reference tree (9.71/11.71 GB, 82.92%).
==> Step 5 of 9: Caching likelihood information on reference tree (10.28/11.71 GB, 87.78%).
==> Step 5 of 9: Caching likelihood information on reference tree (10.85/11.71 GB, 92.63%).
==> Step 5 of 9: Caching likelihood information on reference tree (11.42/11.71 GB, 97.48%).
==> Step 6 of 9: Pulling exponents.                                                        
==> Step 7 of 9: Preparing the edges for baseball.
==> Step 8 of 9: Placing genomes.                 
==> Step 9 of 9: placing genome 1 of 2 (50.00%).
==> Step 9 of 9: placing genome 2 of 2 (100.00%).
                                                 
[2022-07-28 11:44:05] INFO: Calculating RED values based on reference tree.
[2022-07-28 11:44:06] TASK: Traversing tree to determine classification method.

==> Processed 0/2 genomes (0%) |               | [?genome/s, ETA ?]
                                                                   
[2022-07-28 11:44:06] INFO: Completed 2 genomes in 0.00 seconds (508.28 genomes/second).
[2022-07-28 11:44:06] TASK: Calculating average nucleotide identity using FastANI (v1.33).

==> Processed 0/50 comparisons (0%) |               | [?comparison/s, ETA ?]
==> Processed 1/50 comparisons (2%) |â–Ž              | [ 2.12s/comparison, ETA 01:43]
==> Processed 2/50 comparisons (4%) |â–Œ              | [ 1.13s/comparison, ETA 00:54]
==> Processed 4/50 comparisons (8%) |â–ˆâ–             | [ 1.78comparison/s, ETA 00:25]
==> Processed 6/50 comparisons (12%) |â–ˆâ–Š             | [ 2.61comparison/s, ETA 00:16]
==> Processed 7/50 comparisons (14%) |â–ˆâ–ˆ             | [ 2.15comparison/s, ETA 00:20]
==> Processed 8/50 comparisons (16%) |â–ˆâ–ˆâ–            | [ 2.31comparison/s, ETA 00:18]
==> Processed 9/50 comparisons (18%) |â–ˆâ–ˆâ–‹            | [ 1.91comparison/s, ETA 00:21]
==> Processed 10/50 comparisons (20%) |â–ˆâ–ˆâ–ˆ            | [ 2.10comparison/s, ETA 00:19]
==> Processed 11/50 comparisons (22%) |â–ˆâ–ˆâ–ˆâ–Ž           | [ 2.27comparison/s, ETA 00:17]
==> Processed 13/50 comparisons (26%) |â–ˆâ–ˆâ–ˆâ–‰           | [ 2.69comparison/s, ETA 00:13]
==> Processed 15/50 comparisons (30%) |â–ˆâ–ˆâ–ˆâ–ˆâ–Œ          | [ 3.14comparison/s, ETA 00:11]
==> Processed 16/50 comparisons (32%) |â–ˆâ–ˆâ–ˆâ–ˆâ–Š          | [ 3.11comparison/s, ETA 00:10]
==> Processed 17/50 comparisons (34%) |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆ          | [ 2.51comparison/s, ETA 00:13]
==> Processed 18/50 comparisons (36%) |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–         | [ 2.60comparison/s, ETA 00:12]
==> Processed 19/50 comparisons (38%) |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‹         | [ 2.79comparison/s, ETA 00:11]
==> Processed 20/50 comparisons (40%) |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ         | [ 2.92comparison/s, ETA 00:10]
==> Processed 21/50 comparisons (42%) |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Ž        | [ 2.82comparison/s, ETA 00:10]
==> Processed 23/50 comparisons (46%) |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‰        | [ 2.91comparison/s, ETA 00:09]
==> Processed 24/50 comparisons (48%) |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–       | [ 2.96comparison/s, ETA 00:08]
==> Processed 25/50 comparisons (50%) |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Œ       | [ 2.24comparison/s, ETA 00:11]
==> Processed 26/50 comparisons (52%) |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Š       | [ 2.39comparison/s, ETA 00:10]
==> Processed 27/50 comparisons (54%) |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ       | [ 2.52comparison/s, ETA 00:09]
==> Processed 29/50 comparisons (58%) |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‹      | [ 2.58comparison/s, ETA 00:08]
==> Processed 30/50 comparisons (60%) |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ      | [ 2.66comparison/s, ETA 00:07]
==> Processed 31/50 comparisons (62%) |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Ž     | [ 2.82comparison/s, ETA 00:06]
==> Processed 32/50 comparisons (64%) |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Œ     | [ 2.81comparison/s, ETA 00:06]
==> Processed 33/50 comparisons (66%) |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‰     | [ 2.66comparison/s, ETA 00:06]
==> Processed 36/50 comparisons (72%) |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Š    | [ 3.17comparison/s, ETA 00:04]
==> Processed 37/50 comparisons (74%) |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ    | [ 2.79comparison/s, ETA 00:04]
==> Processed 38/50 comparisons (76%) |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–   | [ 2.72comparison/s, ETA 00:04]
==> Processed 39/50 comparisons (78%) |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‹   | [ 2.68comparison/s, ETA 00:04]
==> Processed 40/50 comparisons (80%) |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ   | [ 2.61comparison/s, ETA 00:03]
==> Processed 41/50 comparisons (82%) |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Ž  | [ 2.65comparison/s, ETA 00:03]
==> Processed 42/50 comparisons (84%) |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Œ  | [ 2.80comparison/s, ETA 00:02]
==> Processed 43/50 comparisons (86%) |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‰  | [ 2.22comparison/s, ETA 00:03]
==> Processed 44/50 comparisons (88%) |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ– | [ 2.36comparison/s, ETA 00:02]
==> Processed 45/50 comparisons (90%) |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Œ | [ 2.50comparison/s, ETA 00:02]
==> Processed 47/50 comparisons (94%) |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ | [ 2.87comparison/s, ETA 00:01]
==> Processed 48/50 comparisons (96%) |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–| [ 2.96comparison/s, ETA 00:00]
==> Processed 49/50 comparisons (98%) |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‹| [ 2.42comparison/s, ETA 00:00]
                                                                                      

==> Processed 50/50 comparisons (100%) |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| [ 2.42comparison/s, ETA 00:00]
                                                                                       
[2022-07-28 11:44:25] INFO: Completed 50 comparisons in 19.43 seconds (2.57 comparisons/second).
[2022-07-28 11:44:25] INFO: 0 genome(s) have been classified using FastANI and pplacer.
[2022-07-28 11:44:25] ERROR: Uncontrolled exit resulting from an unexpected error.

================================================================================
EXCEPTION: FileExistsError
  MESSAGE: [Errno 17] File exists: 'classify/gtdbtk.ar122.summary.tsv' -> 'genomes/taxonomy/gtdb/gtdbtk.ar122.summary.tsv'
________________________________________________________________________________

Traceback (most recent call last):
  File "/lustre/projects/Research_Project-T115468/atlas_databases/conda_envs/1e49aab428742b0674475556e0f9f646/lib/python3.10/site-packages/gtdbtk/__main__.py", line 95, in main
    gt_parser.parse_options(args)
  File "/lustre/projects/Research_Project-T115468/atlas_databases/conda_envs/1e49aab428742b0674475556e0f9f646/lib/python3.10/site-packages/gtdbtk/main.py", line 754, in parse_options
    self.classify(options)
  File "/lustre/projects/Research_Project-T115468/atlas_databases/conda_envs/1e49aab428742b0674475556e0f9f646/lib/python3.10/site-packages/gtdbtk/main.py", line 455, in classify
    classify.run(genomes,
  File "/lustre/projects/Research_Project-T115468/atlas_databases/conda_envs/1e49aab428742b0674475556e0f9f646/lib/python3.10/site-packages/gtdbtk/classify.py", line 477, in run
    symlink_f(PATH_AR122_SUMMARY_OUT.format(prefix=prefix),
  File "/lustre/projects/Research_Project-T115468/atlas_databases/conda_envs/1e49aab428742b0674475556e0f9f646/lib/python3.10/site-packages/gtdbtk/tools.py", line 200, in symlink_f
    os.symlink(src, dst)
FileExistsError: [Errno 17] File exists: 'classify/gtdbtk.ar122.summary.tsv' -> 'genomes/taxonomy/gtdb/gtdbtk.ar122.summary.tsv'
================================================================================

```

**Comment by jmtsuji** [comment]
@skeffington You could delete the entire `genomes/taxonomy/gtdb` folder and then re-run -- that should work in theory.

**Comment by skeffington** [comment]
That worked! Thanks agin

**Comment by jmtsuji** [comment]
Glad to hear!
