### ISSUE TITLE
Error in rule

### ISSUE THREAD

**Issue by CynthiaChibani** [metagenome-atlas/atlas#584]
Dear Silas,
I am running atlas assembly step, i can see I have assemblies for some of the samples and then some not. I get this error:

(atlasenv) atlas run assembly --ri

[Atlas] INFO: Atlas version: 2.9.1
Building DAG of jobs...
Traceback (most recent call last):
  File "/gxfs_home/cau/sunam162/.conda/envs/ATLAS/envs/atlasenv/lib/python3.8/site-packages/snakemake/__init__.py", line 722, in snakemake
    success = workflow.execute(
  File "/gxfs_home/cau/sunam162/.conda/envs/ATLAS/envs/atlasenv/lib/python3.8/site-packages/snakemake/workflow.py", line 1051, in execute
    dag.warn_about_changes(quiet)
  File "/gxfs_home/cau/sunam162/.conda/envs/ATLAS/envs/atlasenv/lib/python3.8/site-packages/snakemake/dag.py", line 2289, in warn_about_changes
    changed = self.get_outputs_with_changes(
  File "/gxfs_home/cau/sunam162/.conda/envs/ATLAS/envs/atlasenv/lib/python3.8/site-packages/snakemake/dag.py", line 2279, in get_outputs_with_changes
    changed = list(chain(*map(is_changed, self.jobs)))
  File "/gxfs_home/cau/sunam162/.conda/envs/ATLAS/envs/atlasenv/lib/python3.8/site-packages/snakemake/persistence.py", line 477, in <genexpr>
    return (f for f in job.expanded_output if func(job, file=f))
  File "/gxfs_home/cau/sunam162/.conda/envs/ATLAS/envs/atlasenv/lib/python3.8/site-packages/snakemake/persistence.py", line 348, in _code_changed
    recorded = self.code(file)
  File "/gxfs_home/cau/sunam162/.conda/envs/ATLAS/envs/atlasenv/lib/python3.8/site-packages/snakemake/persistence.py", line 323, in code
    return self.metadata(path).get("code")
  File "/gxfs_home/cau/sunam162/.conda/envs/ATLAS/envs/atlasenv/lib/python3.8/site-packages/snakemake/persistence.py", line 302, in metadata
    return self._read_record(self._metadata_path, path)
  File "/gxfs_home/cau/sunam162/.conda/envs/ATLAS/envs/atlasenv/lib/python3.8/site-packages/snakemake/persistence.py", line 423, in _read_record_uncached
    return json.load(f)
  File "/gxfs_home/cau/sunam162/.conda/envs/ATLAS/envs/atlasenv/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/gxfs_home/cau/sunam162/.conda/envs/ATLAS/envs/atlasenv/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/gxfs_home/cau/sunam162/.conda/envs/ATLAS/envs/atlasenv/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 1371 (char 1370)
[Atlas] CRITICAL: Command 'snakemake --snakefile /gxfs_home/cau/sunam162/.conda/envs/ATLAS/envs/atlasenv/lib/python3.8/site-packages/atlas/workflow/Snakefile --directory /gxfs_work1/fs2/work-sh1/sunam162/arch_MAGs_2 --jobs 64 --rerun-incomplete --configfile '/gxfs_work1/fs2/work-sh1/sunam162/arch_MAGs_2/config.yaml' --nolock   --use-conda --conda-prefix /gxfs_work1/cau/sunam162/arch_MAGs_2/databases/conda_envs    --resources mem=716 mem_mb=734087 java_mem=609   --scheduler greedy  assembly  --ri ' returned non-zero exit status 1.

I would appreciate your input.
best,
Cynthia

**Comment by SilasK** [comment]
You could also update atlas `mamba install metagenome-atlas=2.12`

**Comment by CynthiaChibani** [comment]
Dear Silas, we did update to metagenome-atlas=2.12 and snakemake version is 7.15.2 and the problem is and snakemake-minimal. 
The issue there is, that:
- package metagenome-atlas-2.12.0-pyhdfd78af_1 requires snakemake-minimal >=7.15.1,<7.16, but none of the providers can be installed

**Comment by SilasK** [comment]
Atlas v2.13 will be available soon. if you continue having problems let's dicuss in #586
