### ISSUE TITLE
Error in rule combine_egg_nogg_annotations

### ISSUE THREAD

**Issue by mladen5000** [metagenome-atlas/atlas#653]
- [ x] I checked and didn't found a related issue,e.g. while typing the title
- [x ] ** I got an error in the following rule(s):** ` Error in rule combine_egg_nogg_annotations:
 

Error executing rule combine_egg_nogg_annotations on cluster (jobid: 6974, external: 1127400, jobscript: /projects/com_perkinsd/common/qc-antibiotics-atlas/.snakemake/tmp.eqda_xzd/snakejob.combine_egg_nogg_annotations.6974.sh). For error details see the cluster log and the log files of the involved rule(s).
Exiting because a job execution failed. Look above for error message `

- [x] I checked the log files indicated indicated in the error message (and the cluster logs if submitted to a cluster)
 

Here is the relevant log output:

```
Traceback (most recent call last):
  File "/projects/com_perkinsd/mrasic2/myatlas/atlas/atlas/workflow/rules/genecatalog.smk", line 1009, in __rule_combine_egg_nogg_annotations
  File "/home/mrasic2/.conda/envs/atlas-dev/lib/python3.11/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mrasic2/.conda/envs/atlas-dev/lib/python3.11/site-packages/pandas/core/frame.py", line 2976, in to_parquet
    return to_parquet(
           ^^^^^^^^^^^
  File "/home/mrasic2/.conda/envs/atlas-dev/lib/python3.11/site-packages/pandas/io/parquet.py", line 430, in to_parquet
    impl.write(
  File "/home/mrasic2/.conda/envs/atlas-dev/lib/python3.11/site-packages/pandas/io/parquet.py", line 174, in write
    table = self.api.Table.from_pandas(df, **from_pandas_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/table.pxi", line 3475, in pyarrow.lib.Table.from_pandas
  File "/home/mrasic2/.conda/envs/atlas-dev/lib/python3.11/site-packages/pyarrow/pandas_compat.py", line 624, in dataframe_to_arrays
    arrays[i] = maybe_fut.result()
                ^^^^^^^^^^^^^^^^^^
  File "/home/mrasic2/.conda/envs/atlas-dev/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/mrasic2/.conda/envs/atlas-dev/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/mrasic2/.conda/envs/atlas-dev/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mrasic2/.conda/envs/atlas-dev/lib/python3.11/site-packages/pyarrow/pandas_compat.py", line 598, in convert_column
    raise e
  File "/home/mrasic2/.conda/envs/atlas-dev/lib/python3.11/site-packages/pyarrow/pandas_compat.py", line 592, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/array.pxi", line 316, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 83, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 123, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ("Expected bytes, got a 'float' object", 'Conversion failed for column Seed_evalue with type object')



```

** Atlas version**
2.15 or 2.16.1
**Additional context**

**Comment by SilasK** [comment]
This is likely due to the new pandas. 
Probably there is a NA value somewhere but in the Seed_Evalue
