### ISSUE TITLE
atlas downdload fail 

### ISSUE THREAD

**Issue by jowodo** [metagenome-atlas/atlas#700]
- [x] I checked and didn't found a related issue,e.g. while typing the title 
- [x] ** I got an error in the following rule(s): `atlas download --db-dir $DBDIR`** 

```
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/scratch/mirror/atlas/2.18.1/conda_envs/970bf81dc2fb89a4cccba899825a84ec_/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/scratch/mirror/atlas/2.18.1/conda_envs/970bf81dc2fb89a4cccba899825a84ec_/lib/python3.8/ssl.py", line 1274, in recv_into
  File "/scratch/mirror/atlas/2.18.1/conda_envs/970bf81dc2fb89a4cccba899825a84ec_/lib/python3.8/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/scratch/mirror/atlas/2.18.1/conda_envs/970bf81dc2fb89a4cccba899825a84ec_/lib/python3.8/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/scratch/mirror/atlas/2.18.1/conda_envs/970bf81dc2fb89a4cccba899825a84ec_/lib/python3.8/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/scratch/mirror/atlas/2.18.1/conda_envs/970bf81dc2fb89a4cccba899825a84ec_/lib/python3.8/site-packages/urllib3/connectionpool.py", line 538, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/scratch/mirror/atlas/2.18.1/conda_envs/970bf81dc2fb89a4cccba899825a84ec_/lib/python3.8/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='zenodo.org', port=443): Read timed out. (read timeout=15.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/mirror/atlas/2.18.1/conda_envs/970bf81dc2fb89a4cccba899825a84ec_/lib/python3.8/site-packages/checkm2/zenodo_backpack.py", line 164, in _retrieve_record_ID
    r = requests.get(DOI, timeout=15.)
  File "/scratch/mirror/atlas/2.18.1/conda_envs/970bf81dc2fb89a4cccba899825a84ec_/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/scratch/mirror/atlas/2.18.1/conda_envs/970bf81dc2fb89a4cccba899825a84ec_/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/scratch/mirror/atlas/2.18.1/conda_envs/970bf81dc2fb89a4cccba899825a84ec_/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/scratch/mirror/atlas/2.18.1/conda_envs/970bf81dc2fb89a4cccba899825a84ec_/lib/python3.8/site-packages/requests/sessions.py", line 725, in send    history = [resp for resp in gen]
  File "/scratch/mirror/atlas/2.18.1/conda_envs/970bf81dc2fb89a4cccba899825a84ec_/lib/python3.8/site-packages/requests/sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
  File "/scratch/mirror/atlas/2.18.1/conda_envs/970bf81dc2fb89a4cccba899825a84ec_/lib/python3.8/site-packages/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/scratch/mirror/atlas/2.18.1/conda_envs/970bf81dc2fb89a4cccba899825a84ec_/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/scratch/mirror/atlas/2.18.1/conda_envs/970bf81dc2fb89a4cccba899825a84ec_/lib/python3.8/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='zenodo.org', port=443): Read timed out. (read timeout=15.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/mirror/atlas/2.18.1/conda_envs/970bf81dc2fb89a4cccba899825a84ec_/bin/checkm2", line 280, in <module>
    fileManager.DiamondDB().download_database(args.path)
  File "/scratch/mirror/atlas/2.18.1/conda_envs/970bf81dc2fb89a4cccba899825a84ec_/lib/python3.8/site-packages/checkm2/fileManager.py", line 127, in download_database
    backpack_downloader.download_and_extract(download_location, DOI, progress_bar=True, no_check_version=False)
  File "/scratch/mirror/atlas/2.18.1/conda_envs/970bf81dc2fb89a4cccba899825a84ec_/lib/python3.8/site-packages/checkm2/zenodo_backpack.py", line 46, in download_and_extract
    recordID = self._retrieve_record_ID(DOI)
  File "/scratch/mirror/atlas/2.18.1/conda_envs/970bf81dc2fb89a4cccba899825a84ec_/lib/python3.8/site-packages/checkm2/zenodo_backpack.py", line 166, in _retrieve_record_ID
    raise ZenodoConnectionException('Connection error: {}'.format(e))
checkm2.zenodo_backpack.ZenodoConnectionException: Connection error: HTTPSConnectionPool(host='zenodo.org', port=443): Read timed out. (read timeout=15.0)
================================================================================

Removing output files of failed job checkm2_download_db since they might be corrupted:
/scratch/mirror/atlas/2.18.1/CheckM2
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

** Atlas version**
2.18.1

**Comment by SilasK** [comment]
Seems like a problem of Internet connection. Did other download steps succede?

**Comment by jowodo** [comment]
yes, conda installation works without problem! It seems that the directory structure for eggNOG is more fine grained than just major version 
http://eggnog6.embl.de/download/emapperdb-5.0.2/ instead of http://eggnog6.embl.de/download/emapperdb-5

**Comment by SilasK** [comment]
Where are we here again. you had an error in checkm2 isn't it or egggNog?
Do you need the eggNOG really?

**Comment by jowodo** [comment]
Hi, 
I retried the command:
```
atlas download --db-dir $DBDIR
```
and it worked now. May have been related to connection problems after all.
