### ISSUE TITLE
Error in rule build_qc_report: ModuleNotFoundError: No module named 'numpy._version'

### ISSUE THREAD

**Issue by the-eon-flux** [metagenome-atlas/atlas#722]
Hi Silas,

Thank you for maintaining ATLAS all this while. :)
I am getting an error  (probably stupid) and cannot seem to debug it. Can you please help?

- [x] I checked and didn't found a related issue,e.g. while typing the title
- [x] ** I got an error in the following rule(s):**  `Error in rule build_qc_report:`

- [x] I checked the log files indicated in the error message (and the cluster logs if submitted to a cluster)

The error message should looks like this: 
```

Error in rule build_qc_report:
    jobid: 1071
    input: SRR7947996/sequence_quality_control/read_stats/QC.zip, SRR7947997/sequence_quality_control/read_stats/QC.zip, SRR7947998/sequence_quality_control/read_stats/QC.zip, SRR7947999/sequence_quality_control/read_stats/QC.zip, SRR7948000/sequence_quality_control/read_stats/QC.zip, SRR7948001/sequence_quality_control/read_stats/QC.zip, SRR7948002/sequence_quality_control/read_stats/QC.zip, SRR7948003/sequence_quality_control/read_stats/QC.zip, SRR7948004/sequence_quality_control/read_stats/QC.zip, SRR7948005/sequence_quality_control/read_stats/QC.zip, SRR7948006/sequence_quality_control/read_stats/QC.zip, SRR7948007/sequence_quality_control/read_stats/QC.zip, SRR7948008/sequence_quality_control/read_stats/QC.zip, SRR7948009/sequence_quality_control/read_stats/QC.zip, SRR7948010/sequence_quality_control/read_stats/ ...
    output: reports/QC_report.html
    log: logs/QC/report.log (check log file(s) for error details)
    conda-env: /home/isilon/users/o_shinde/References_local/ATLAS_ref/conda_envs/7828e8bdcb4de8a957df391d07859626_

```
The `log: logs/QC/report.log` file is empty.

Here is the relevant log output:

The cluster log is the same as this: [Cluster_log_slurm-709003.log](https://github.com/user-attachments/files/15510968/Cluster_log_slurm-709003.log)

```

Traceback (most recent call last):
  File "/home/isilon/users/o_shinde/References_local/ATLAS_ref/conda_envs/7828e8bdcb4de8a957df391d07859626_/lib/python3.9/site-packages/numpy/__init__.py", line 125, in <module>
    from numpy.__config__ import show as show_config
  File "/home/isilon/users/o_shinde/References_local/ATLAS_ref/conda_envs/7828e8bdcb4de8a957df391d07859626_/lib/python3.9/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "/home/isilon/users/o_shinde/References_local/ATLAS_ref/conda_envs/7828e8bdcb4de8a957df391d07859626_/lib/python3.9/site-packages/numpy/core/__init__.py", line 9, in <module>
    from numpy.version import version as __version__
  File "/home/isilon/users/o_shinde/References_local/ATLAS_ref/conda_envs/7828e8bdcb4de8a957df391d07859626_/lib/python3.9/site-packages/numpy/version.py", line 3, in <module>
    from ._version import get_versions
ModuleNotFoundError: No module named 'numpy._version'


Traceback (most recent call last):
  File "/home/isilon/ag_cme/o_shinde/Batch_LRTB5_PRJNA494034/.snakemake/scripts/tmpeo76c93i.qc_report.py", line 3, in <module>
    import sys; sys.path.extend(['/home/gpfs/o_shinde/Softwares_Tejus/conda_mamba/envs/atlas_v2.18/lib/python3.10/site-packages', '/home/gpfs/o_shinde/.cache/snakemake/snakemake/source-cache/runtime-cache/tmpcbb7ljwz/file/home/gpfs/o_shinde/Softwares_Tejus/conda_mamba/envs/atlas_v2.18/lib/python3.10/site-packages/atlas/workflow/rules/../report', ...

../conda_mamba/envs/atlas_v2.18/lib/python3.10/site-packages/atlas/workflow/rules/../report\x94ub.'); from snakemake.logging import logger; logger.printshellcmds = False; __real_file__ = __file__; __file__ = '/home/gpfs/o_shinde/Softwares_Tejus/conda_mamba/envs/atlas_v2.18/lib/python3.10/site-packages/atlas/workflow/report/qc_report.py';
  File "/home/isilon/users/o_shinde/References_local/ATLAS_ref/conda_envs/7828e8bdcb4de8a957df391d07859626_/lib/python3.9/site-packages/numpy/__init__.py", line 130, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.


```

**Atlas version:** atlas, version 2.18.0
**Additional context**
- I am running ATLAS on a computing cluster with slurm job scheduler. The ATLAS env is personally installed.
- I tried to run it on cluster and also locally (since it's just 2 rules) but it didn't work. 
- I tried removing the env `7828e8bdcb4de8a957df391d07859626_` and re-running `atlas qc`, which reinstalled the conda env and the error was still there. 
- I activated the env `7828e8bdcb4de8a957df391d07859626_` and installed `numpy` again with `pip3 install numpy` bit it also didn't work in my case.

Please recommend a workaround/solution for this.

**Comment by the-eon-flux** [comment]
Never mind. I found the problem. I had made a copy of the ATLAS reference files (genome indexes, databases, etc including the conda env paths). The cluster configuration didn't allow using the other path. I changed it back to the original one and it works now.

**Comment by SilasK** [comment]
thank you for posting anyway.
